import {
  Book,
  BookOpen,
  Briefcase,
  Bus,
  CalendarDays,
  Clock,
  Coffee,
  GraduationCap,
  Hand,
  Heart,
  Home,
  Landmark,
  MapPin,
  MessageCircle,
  Music,
  Newspaper,
  Plane,
  ShoppingCart,
  Stethoscope,
  Sun,
  Users,
  Utensils,
  Wrench,
  Globe,
  Building2,
  Leaf,
  Laptop,
  PartyPopper,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  book: Book,
  "book-open": BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  calendar: CalendarDays,
  clock: Clock,
  coffee: Coffee,
  "graduation-cap": GraduationCap,
  hand: Hand,
  heart: Heart,
  home: Home,
  landmark: Landmark,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  music: Music,
  newspaper: Newspaper,
  plane: Plane,
  "shopping-cart": ShoppingCart,
  stethoscope: Stethoscope,
  sun: Sun,
  users: Users,
  utensils: Utensils,
  wrench: Wrench,
  globe: Globe,
  building: Building2,
  leaf: Leaf,
  laptop: Laptop,
  party: PartyPopper,
};

export function iconFor(name: string): LucideIcon {
  return ICON_MAP[name] ?? Book;
}
