import type { GrammarSeed } from "./types";

export const GRAMMAR_A: GrammarSeed[] = [
  {
    slug: "personalpronomen-sein-haben",
    levelCode: "A1",
    title: "Personalpronomen & sein/haben",
    category: "Verben & Konjugation",
    summary: "The pronouns ich, du, er… and the two most important verbs in German: sein (to be) and haben (to have).",
    blocks: [
      { type: "text", md: "Every German sentence starts here. The **personal pronouns** tell us who acts, and **sein** and **haben** are the backbone verbs — you'll use them in almost every conversation, and later to build the past tense." },
      { type: "table", title: "sein & haben im Präsens", headers: ["Pronomen", "sein (to be)", "haben (to have)"], rows: [["ich", "bin", "habe"], ["du", "bist", "hast"], ["er/sie/es", "ist", "hat"], ["wir", "sind", "haben"], ["ihr", "seid", "habt"], ["sie/Sie", "sind", "haben"]] },
      { type: "callout", variant: "grammar", title: "du, ihr oder Sie?", md: "- **du** — one person you know well (friends, family, children)\n- **ihr** — several people you know well\n- **Sie** — formal, one OR several people (always capitalized!)" },
      { type: "examples", title: "So klingt das", items: [
        { de: "Ich bin Anna und ich bin 25 Jahre alt.", en: "I'm Anna and I'm 25 years old." },
        { de: "Bist du müde?", en: "Are you tired?" },
        { de: "Wir haben heute keine Zeit.", en: "We don't have time today." },
        { de: "Sind Sie Herr Müller?", en: "Are you Mr. Müller? (formal)" },
      ] },
      { type: "mistakes", items: [
        { wrong: "Ich bin 25 Jahre.", right: "Ich bin 25 (Jahre alt).", why: "Either just the number or the full 'Jahre alt' — never 'Jahre' alone." },
        { wrong: "Du bist haben ein Auto?", right: "Hast du ein Auto?", why: "One verb per idea! For possession use haben, not sein + haben." },
        { wrong: "sie ist meine Lehrerin? (about Mrs. Weber, formal)", right: "Sind Sie meine Lehrerin?", why: "Formal 'Sie' is always capitalized and takes the plural verb form." },
      ] },
      { type: "exercise", slug: "a1-sein-haben-gap" },
    ],
    cheatSheet: {
      title: "sein & haben auf einen Blick",
      points: [
        "ich bin / du bist / er ist — wir sind / ihr seid / sie sind",
        "ich habe / du hast / er hat — wir haben / ihr habt / sie haben",
        "Sie (formal) always takes the sie-plural form: Sie sind, Sie haben",
        "Age, feelings, professions → sein. Possession, hunger, time → haben.",
      ],
    },
  },
  {
    slug: "praesens-regelmaessig",
    levelCode: "A1",
    title: "Präsens: regelmäßige Verben",
    category: "Verben & Konjugation",
    summary: "How to conjugate regular verbs like wohnen, machen and lernen — one pattern that unlocks hundreds of verbs.",
    blocks: [
      { type: "text", md: "Take the infinitive (**wohnen**), cut off **-en** to get the stem (**wohn-**), then add the personal ending. This single pattern works for the vast majority of German verbs." },
      { type: "table", title: "Die Endungen", headers: ["Pronomen", "Endung", "wohnen", "arbeiten*"], rows: [["ich", "-e", "wohne", "arbeite"], ["du", "-st", "wohnst", "arbeitest"], ["er/sie/es", "-t", "wohnt", "arbeitet"], ["wir", "-en", "wohnen", "arbeiten"], ["ihr", "-t", "wohnt", "arbeitet"], ["sie/Sie", "-en", "wohnen", "arbeiten"]], caption: "*Stems ending in -t or -d insert an extra e: du arbeit-e-st, er arbeit-e-t." },
      { type: "callout", variant: "tip", title: "Das Verb ist immer Position 2", md: "In a normal statement the conjugated verb is **always the second element**: *Ich **wohne** in Berlin.* / *Heute **lerne** ich Deutsch.* — even when the sentence starts with something else!" },
      { type: "examples", items: [
        { de: "Ich lerne jeden Tag zwanzig Minuten Deutsch.", en: "I study German twenty minutes every day." },
        { de: "Woher kommst du?", en: "Where do you come from?" },
        { de: "Er spielt am Wochenende Fußball.", en: "He plays football at the weekend." },
        { de: "Heute arbeitet sie nicht.", en: "She isn't working today.", note: "Verb stays in position 2!" },
      ] },
      { type: "mistakes", items: [
        { wrong: "Du wohnt in Hamburg.", right: "Du wohnst in Hamburg.", why: "du always takes -st." },
        { wrong: "Heute ich lerne Deutsch.", right: "Heute lerne ich Deutsch.", why: "The verb must stay in position 2 — the subject moves behind it." },
      ] },
      { type: "exercise", slug: "a1-praesens-endungen" },
    ],
    cheatSheet: {
      title: "Präsens-Endungen",
      points: ["Stem = Infinitiv minus -en", "ich -e · du -st · er -t · wir -en · ihr -t · sie -en", "Stems on -t/-d: extra e for du/er/ihr (arbeitest)", "Statement = verb in position 2. Always."],
      table: { headers: ["ich", "du", "er", "wir", "ihr", "sie"], rows: [["-e", "-st", "-t", "-en", "-t", "-en"]] },
    },
  },
  {
    slug: "artikel-genus",
    levelCode: "A1",
    title: "Artikel: der, die, das",
    category: "Nomen & Artikel",
    summary: "Every German noun has a gender. Learn the system, the signals — and why you should always learn nouns WITH their article.",
    blocks: [
      { type: "text", md: "German nouns are **masculine (der)**, **feminine (die)** or **neuter (das)**. Grammatical gender is mostly arbitrary (*das Mädchen* — the girl is neuter!), so the golden rule is: **never learn a noun without its article**." },
      { type: "table", title: "Bestimmt & unbestimmt", headers: ["Genus", "bestimmt", "unbestimmt", "Beispiel"], rows: [["maskulin", "der", "ein", "der Tisch → ein Tisch"], ["feminin", "die", "eine", "die Lampe → eine Lampe"], ["neutral", "das", "ein", "das Buch → ein Buch"], ["Plural", "die", "— (keine)", "die Bücher"]] },
      { type: "callout", variant: "tip", title: "Endungs-Signale (funktionieren meistens!)", md: "- **-ung, -heit, -keit, -schaft, -ion** → fast immer **die** (die Wohnung, die Nation)\n- **-chen, -lein** → immer **das** (das Mädchen, das Brötchen)\n- **-er** (Personen), Tage, Monate, Jahreszeiten → meist **der** (der Lehrer, der Montag)" },
      { type: "examples", items: [
        { de: "Der Kaffee ist heiß.", en: "The coffee is hot." },
        { de: "Ich habe eine Frage.", en: "I have a question." },
        { de: "Das ist ein Foto von meiner Familie.", en: "That's a photo of my family." },
        { de: "Die Kinder spielen draußen.", en: "The children are playing outside.", note: "Plural is always 'die'." },
      ] },
      { type: "mistakes", items: [
        { wrong: "Ich kaufe eine Brot.", right: "Ich kaufe ein Brot.", why: "Brot is neuter: das Brot → ein Brot." },
        { wrong: "Die Mädchen ist nett. (one girl)", right: "Das Mädchen ist nett.", why: "-chen words are always neuter — even for people!" },
      ] },
      { type: "exercise", slug: "a1-artikel-match" },
    ],
    cheatSheet: {
      title: "Artikel-Signale",
      points: ["Learn every noun WITH der/die/das — no exceptions", "-ung/-heit/-keit/-ion → die", "-chen/-lein → das", "Plural → immer die", "Color-code your notes: der=blue, die=red, das=green"],
    },
  },
  {
    slug: "nominativ-akkusativ",
    levelCode: "A1",
    title: "Nominativ & Akkusativ",
    category: "Kasus",
    summary: "Your first two cases: the subject (Nominativ) and the direct object (Akkusativ) — where only 'der' changes to 'den'.",
    blocks: [
      { type: "text", md: "The **Nominativ** is the subject — who does something. The **Akkusativ** is the direct object — what the action lands on. The great news for beginners: in the Akkusativ **only masculine changes** (der → den, ein → einen)." },
      { type: "table", title: "Nominativ vs. Akkusativ", headers: ["Genus", "Nominativ", "Akkusativ"], rows: [["maskulin", "der / ein", "den / einen ⚠️"], ["feminin", "die / eine", "die / eine"], ["neutral", "das / ein", "das / ein"], ["Plural", "die", "die"]] },
      { type: "examples", items: [
        { de: "Der Mann kauft den Apfel.", en: "The man buys the apple.", note: "Mann = subject (Nom.), Apfel = object (Akk.)" },
        { de: "Ich habe einen Bruder.", en: "I have a brother.", note: "haben always takes Akkusativ" },
        { de: "Siehst du das Auto?", en: "Do you see the car?", note: "neuter: no change" },
        { de: "Wir trinken eine Cola.", en: "We're drinking a cola.", note: "feminine: no change" },
      ] },
      { type: "callout", variant: "grammar", title: "Verben mit Akkusativ", md: "These common verbs always take Akkusativ: **haben, brauchen, kaufen, essen, trinken, sehen, suchen, finden, lieben, es gibt**." },
      { type: "mistakes", items: [
        { wrong: "Ich habe ein Hund.", right: "Ich habe einen Hund.", why: "Hund is masculine and object of haben → einen." },
        { wrong: "Er kauft der Computer.", right: "Er kauft den Computer.", why: "der → den in the Akkusativ." },
      ] },
      { type: "exercise", slug: "a1-akkusativ-gap" },
    ],
    cheatSheet: {
      title: "Der Akkusativ-Trick",
      points: ["Only masculine changes: der→den, ein→einen", "Feminine, neuter, plural: identical to Nominativ", "Ask 'wen oder was?' (whom/what?) to find the Akkusativ object", "es gibt + Akkusativ: Es gibt einen Park."],
    },
  },
  {
    slug: "fragen-stellen",
    levelCode: "A1",
    title: "Fragen: W-Fragen & Ja/Nein-Fragen",
    category: "Satzbau",
    summary: "Two question types, two word orders — the key to every conversation.",
    blocks: [
      { type: "text", md: "**W-Fragen** start with a question word (wer, was, wo, …) and the verb comes second. **Ja/Nein-Fragen** start directly with the verb." },
      { type: "table", title: "Die W-Wörter", headers: ["W-Wort", "Bedeutung", "Beispiel"], rows: [["wer", "who", "Wer ist das?"], ["was", "what", "Was machst du?"], ["wo", "where", "Wo wohnst du?"], ["woher", "where from", "Woher kommen Sie?"], ["wohin", "where to", "Wohin fährst du?"], ["wann", "when", "Wann beginnt der Kurs?"], ["wie", "how", "Wie heißt du?"], ["warum", "why", "Warum lernst du Deutsch?"], ["wie viel(e)", "how much/many", "Wie viel kostet das?"]] },
      { type: "examples", title: "Ja/Nein-Fragen: Verb zuerst!", items: [
        { de: "Kommst du aus Italien?", en: "Do you come from Italy?" },
        { de: "Haben Sie Zeit?", en: "Do you have time?" },
        { de: "Sprichst du Englisch? — Ja, ein bisschen.", en: "Do you speak English? — Yes, a little." },
      ] },
      { type: "callout", variant: "tip", title: "doch — die geniale Antwort", md: "Someone asks negatively: *Hast du **keine** Zeit?* Answer **doch!** = 'yes I do!' — a word English is badly missing." },
      { type: "mistakes", items: [
        { wrong: "Wo du wohnst?", right: "Wo wohnst du?", why: "After the W-word comes the VERB, then the subject." },
        { wrong: "Du kommst aus Spanien?", right: "Kommst du aus Spanien?", why: "Real questions start with the verb (intonation-only questions sound casual)." },
      ] },
      { type: "exercise", slug: "a1-fragen-ordnen" },
    ],
    cheatSheet: {
      title: "Frage-Formeln",
      points: ["W-Frage: W-Wort + Verb + Subjekt + …?", "Ja/Nein-Frage: Verb + Subjekt + …?", "wo = where, woher = from where, wohin = to where", "Negative Frage? Antworte mit doch!"],
    },
  },
  {
    slug: "negation-nicht-kein",
    levelCode: "A1",
    title: "Negation: nicht & kein",
    category: "Satzbau",
    summary: "Two ways to say no: kein negates nouns, nicht negates everything else.",
    blocks: [
      { type: "text", md: "Use **kein/keine** to negate nouns with *ein* or no article (*Ich habe **kein** Auto*). Use **nicht** for verbs, adjectives, and nouns with definite articles (*Das ist **nicht** mein Auto*)." },
      { type: "table", title: "kein deklinieren (wie ein!)", headers: ["Genus", "Nominativ", "Akkusativ"], rows: [["maskulin", "kein", "keinen"], ["feminin", "keine", "keine"], ["neutral", "kein", "kein"], ["Plural", "keine", "keine"]] },
      { type: "examples", items: [
        { de: "Ich habe keine Zeit.", en: "I have no time.", note: "noun with no article → kein" },
        { de: "Er trinkt keinen Kaffee.", en: "He doesn't drink coffee.", note: "masculine Akkusativ → keinen" },
        { de: "Das Hotel ist nicht teuer.", en: "The hotel is not expensive.", note: "adjective → nicht" },
        { de: "Ich komme heute nicht.", en: "I'm not coming today.", note: "verb → nicht at the end" },
      ] },
      { type: "callout", variant: "warning", title: "Wo steht nicht?", md: "**nicht** usually goes to the **end** of a simple sentence — but **before** adjectives and prepositional phrases: *Ich wohne **nicht in Berlin**.*" },
      { type: "mistakes", items: [
        { wrong: "Ich habe nicht ein Auto.", right: "Ich habe kein Auto.", why: "ein + nicht merges into kein." },
        { wrong: "Ich nicht verstehe.", right: "Ich verstehe nicht.", why: "nicht goes after the verb (usually to the end), never before it." },
      ] },
      { type: "exercise", slug: "a1-negation-mcq" },
    ],
    cheatSheet: {
      title: "nicht oder kein?",
      points: ["kein = negates ein-nouns & no-article nouns", "nicht = negates verbs, adjectives, definite nouns", "kein declines exactly like ein (+ plural keine)", "Position of nicht: end of clause, before adjectives/prepositions"],
    },
  },
  {
    slug: "perfekt",
    levelCode: "A2",
    title: "Das Perfekt",
    category: "Verben & Zeiten",
    summary: "The spoken past tense: haben/sein + Partizip II. This is how Germans actually talk about yesterday.",
    blocks: [
      { type: "text", md: "In conversation, Germans talk about the past almost exclusively in the **Perfekt**: a helper verb (**haben** or **sein**) in position 2 + the **Partizip II** at the very end.\n\n*Ich **habe** gestern Pizza **gegessen**.*" },
      { type: "table", title: "Partizip II bilden", headers: ["Verbtyp", "Muster", "Beispiele"], rows: [["regelmäßig", "ge + Stamm + t", "machen → gemacht, kaufen → gekauft"], ["unregelmäßig", "ge + Stamm(neu) + en", "essen → gegessen, trinken → getrunken"], ["trennbar", "Präfix + ge + … ", "einkaufen → eingekauft, anrufen → angerufen"], ["-ieren / be-/ver-/er-", "KEIN ge-", "studieren → studiert, bezahlen → bezahlt"]] },
      { type: "callout", variant: "grammar", title: "haben oder sein?", md: "**sein** for movement A→B (gehen, fahren, kommen, fliegen) and state change (aufstehen, einschlafen) + *bleiben, sein, passieren*.\n**haben** for everything else — especially all verbs with an Akkusativ object." },
      { type: "examples", items: [
        { de: "Wir haben am Samstag eingekauft.", en: "We went shopping on Saturday." },
        { de: "Sie ist um sieben Uhr aufgestanden.", en: "She got up at seven o'clock.", note: "state change → sein" },
        { de: "Ich bin nach München gefahren.", en: "I went to Munich.", note: "movement → sein" },
        { de: "Hast du schon bezahlt?", en: "Have you already paid?", note: "be- verb: no ge-" },
      ] },
      { type: "mistakes", items: [
        { wrong: "Ich habe nach Berlin gefahren.", right: "Ich bin nach Berlin gefahren.", why: "Movement from A to B takes sein." },
        { wrong: "Er hat gestudiert.", right: "Er hat studiert.", why: "-ieren verbs never get ge-." },
        { wrong: "Ich habe gegessen Pizza.", right: "Ich habe Pizza gegessen.", why: "The Partizip II goes to the very END of the sentence." },
      ] },
      { type: "exercise", slug: "a2-perfekt-gap" },
    ],
    cheatSheet: {
      title: "Perfekt-Formel",
      points: ["haben/sein (Position 2) + Partizip II (Ende)", "Regular: ge—t · Irregular: ge—en (learn them!)", "sein: movement + state change + bleiben/sein/passieren", "-ieren, be-, ver-, er-, ent-: no ge-"],
      table: { headers: ["Infinitiv", "Partizip II", "Hilfsverb"], rows: [["machen", "gemacht", "haben"], ["essen", "gegessen", "haben"], ["gehen", "gegangen", "sein"], ["aufstehen", "aufgestanden", "sein"]] },
    },
  },
  {
    slug: "dativ",
    levelCode: "A2",
    title: "Der Dativ",
    category: "Kasus",
    summary: "The third case — for indirect objects and after prepositions like mit, von, zu, bei.",
    blocks: [
      { type: "text", md: "The **Dativ** marks the receiver of something (*Ich gebe **dem Mann** das Buch*) and follows certain verbs and prepositions. Its signature sound: **-m** (dem, einem, meinem) and **-n** in the plural." },
      { type: "table", title: "Artikel im Dativ", headers: ["Genus", "bestimmt", "unbestimmt", "Beispiel"], rows: [["maskulin", "dem", "einem", "mit dem Bus"], ["feminin", "der", "einer", "bei der Arbeit"], ["neutral", "dem", "einem", "zu dem (=zum) Kind"], ["Plural", "den +n", "—", "mit den Kindern ⚠️"]] },
      { type: "callout", variant: "grammar", title: "Immer mit Dativ!", md: "These prepositions ALWAYS take Dativ — learn them as a rhyme:\n**aus, bei, mit, nach, seit, von, zu** (+ gegenüber).\n\nHandy contractions: zu dem = **zum**, zu der = **zur**, bei dem = **beim**, von dem = **vom**." },
      { type: "examples", items: [
        { de: "Ich fahre mit dem Fahrrad zur Arbeit.", en: "I ride my bike to work." },
        { de: "Sie wohnt seit einem Jahr bei einer Freundin.", en: "She's been living at a friend's for a year." },
        { de: "Kannst du mir helfen?", en: "Can you help me?", note: "helfen always takes Dativ!" },
        { de: "Der Film gefällt den Kindern.", en: "The children like the film.", note: "Plural + n" },
      ] },
      { type: "mistakes", items: [
        { wrong: "Ich helfe dich.", right: "Ich helfe dir.", why: "helfen, danken, gefallen, gehören take Dativ objects." },
        { wrong: "mit die Kinder", right: "mit den Kindern", why: "mit always takes Dativ; plural Dativ adds -n to the noun." },
      ] },
      { type: "exercise", slug: "a2-dativ-gap" },
    ],
    cheatSheet: {
      title: "Dativ-Merkhilfen",
      points: ["aus-bei-mit-nach-seit-von-zu: always Dativ", "dem/dem/der + den(+n) — masculine & neuter get -m", "Dativ verbs: helfen, danken, gefallen, gehören, antworten", "zum = zu dem · zur = zu der · beim = bei dem"],
    },
  },
  {
    slug: "modalverben",
    levelCode: "A2",
    title: "Modalverben",
    category: "Verben & Konjugation",
    summary: "können, müssen, wollen & Co. — how to express ability, necessity and wishes, with the infinitive at the end.",
    blocks: [
      { type: "text", md: "Modal verbs change the flavor of a sentence: ability (**können**), necessity (**müssen**), permission (**dürfen**), desire (**wollen/möchten**), advice (**sollen**). Structure: modal in **position 2**, main verb as **infinitive at the end**." },
      { type: "table", title: "Konjugation (Singular ist speziell!)", headers: ["", "können", "müssen", "wollen", "dürfen", "sollen", "möchten"], rows: [["ich", "kann", "muss", "will", "darf", "soll", "möchte"], ["du", "kannst", "musst", "willst", "darfst", "sollst", "möchtest"], ["er/sie/es", "kann", "muss", "will", "darf", "soll", "möchte"], ["wir/sie", "können", "müssen", "wollen", "dürfen", "sollen", "möchten"]] },
      { type: "callout", variant: "warning", title: "ich kann, er kann — ohne Endung!", md: "In the singular, modals change their vowel and take **no ending** for ich/er/sie/es. *ich kann* (not ~~könne~~), *er muss* (not ~~musst~~)." },
      { type: "examples", items: [
        { de: "Ich kann sehr gut kochen.", en: "I can cook very well.", note: "kochen → infinitive at the end" },
        { de: "Musst du heute arbeiten?", en: "Do you have to work today?" },
        { de: "Hier darf man nicht parken.", en: "You're not allowed to park here." },
        { de: "Ich möchte einen Termin vereinbaren.", en: "I'd like to make an appointment.", note: "möchten = polite wollen" },
      ] },
      { type: "mistakes", items: [
        { wrong: "Ich kann kochen sehr gut.", right: "Ich kann sehr gut kochen.", why: "The infinitive goes to the very END." },
        { wrong: "Er wills nach Hause.", right: "Er will nach Hause (gehen).", why: "3rd person singular has no -s: er will." },
        { wrong: "Ich will einen Kaffee, bitte. (im Café)", right: "Ich möchte einen Kaffee, bitte.", why: "wollen sounds demanding — möchten is the polite version." },
      ] },
      { type: "exercise", slug: "a2-modalverben-mcq" },
    ],
    cheatSheet: {
      title: "Modalverb-Regeln",
      points: ["Modal Position 2 + Infinitiv am Ende", "Singular: vowel change, no ending (ich kann, er muss)", "möchten = polite wish · wollen = strong will", "man darf nicht = forbidden · man muss nicht = not necessary"],
    },
  },
  {
    slug: "trennbare-verben",
    levelCode: "A2",
    title: "Trennbare Verben",
    category: "Verben & Konjugation",
    summary: "aufstehen, einkaufen, anrufen — verbs that split in two, with the prefix jumping to the end.",
    blocks: [
      { type: "text", md: "Many German verbs carry a prefix (**auf**stehen, **ein**kaufen). In the present tense, the prefix **separates** and flies to the end of the sentence:\n\n*Ich **stehe** um 7 Uhr **auf**.*" },
      { type: "table", title: "Häufige trennbare Präfixe", headers: ["Präfix", "Beispiel", "Bedeutung"], rows: [["auf-", "aufstehen", "to get up"], ["an-", "anrufen", "to call"], ["ein-", "einkaufen", "to shop"], ["mit-", "mitkommen", "to come along"], ["aus-", "aussehen", "to look/appear"], ["ab-", "abfahren", "to depart"], ["zu-", "zuhören", "to listen"], ["vor-", "vorstellen", "to introduce"]] },
      { type: "callout", variant: "grammar", title: "Wann trennt es sich NICHT?", md: "- With **modal verbs**: *Ich muss früh **aufstehen**.* (infinitive stays whole)\n- In the **Perfekt** the ge- squeezes inside: *auf**ge**standen, ein**ge**kauft*\n- Untrennbare Präfixe (be-, ver-, er-, ent-): never split — *Ich **verstehe**.*" },
      { type: "examples", items: [
        { de: "Der Zug fährt um 9:12 Uhr ab.", en: "The train departs at 9:12." },
        { de: "Ich rufe dich morgen an.", en: "I'll call you tomorrow." },
        { de: "Kommst du mit?", en: "Are you coming along?" },
        { de: "Ich habe gestern eingekauft.", en: "I did the shopping yesterday.", note: "Perfekt: ein-GE-kauft" },
      ] },
      { type: "mistakes", items: [
        { wrong: "Ich aufstehe um sieben.", right: "Ich stehe um sieben auf.", why: "The prefix separates and goes to the end." },
        { wrong: "Er hat geanrufen.", right: "Er hat angerufen.", why: "In the Partizip II, ge- goes BETWEEN prefix and stem." },
      ] },
      { type: "exercise", slug: "a2-trennbare-ordnen" },
    ],
    cheatSheet: {
      title: "Trennbar in 4 Regeln",
      points: ["Präsens: prefix → end (Ich stehe … auf.)", "Mit Modalverb: infinitive whole at end (… früh aufstehen.)", "Perfekt: prefix + ge + stem (aufgestanden)", "be-/ver-/er-/ent- never separate"],
    },
  },
  {
    slug: "komparativ-superlativ",
    levelCode: "A2",
    title: "Komparativ & Superlativ",
    category: "Adjektive",
    summary: "schnell, schneller, am schnellsten — comparing things, with the handful of irregulars you must know.",
    blocks: [
      { type: "text", md: "Comparative = adjective + **-er** (*schneller*). Superlative = **am** + adjective + **-sten** (*am schnellsten*). Short adjectives with a/o/u usually take an umlaut: *alt → älter → am ältesten*." },
      { type: "table", title: "Die wichtigsten Unregelmäßigen", headers: ["Grundform", "Komparativ", "Superlativ"], rows: [["gut", "besser", "am besten"], ["gern", "lieber", "am liebsten"], ["viel", "mehr", "am meisten"], ["hoch", "höher", "am höchsten"], ["nah", "näher", "am nächsten"], ["groß", "größer", "am größten"]] },
      { type: "callout", variant: "tip", title: "als vs. wie", md: "- Comparing different things: Komparativ + **als** → *Berlin ist größer **als** Bonn.*\n- Saying things are equal: **so … wie** → *Er ist **so** alt **wie** ich.*" },
      { type: "examples", items: [
        { de: "Der Zug ist schneller als der Bus.", en: "The train is faster than the bus." },
        { de: "Ich trinke lieber Tee als Kaffee.", en: "I prefer tea to coffee.", note: "gern → lieber" },
        { de: "Welches Handy ist am billigsten?", en: "Which phone is the cheapest?" },
        { de: "Deutsch ist nicht so schwer wie viele denken.", en: "German isn't as hard as many think." },
      ] },
      { type: "mistakes", items: [
        { wrong: "Berlin ist mehr groß als Bonn.", right: "Berlin ist größer als Bonn.", why: "German never uses 'mehr' + adjective — always the -er ending." },
        { wrong: "Er ist älter wie ich.", right: "Er ist älter als ich.", why: "After a comparative use als, not wie." },
      ] },
      { type: "exercise", slug: "a2-komparativ-gap" },
    ],
    cheatSheet: {
      title: "Steigerung kompakt",
      points: ["Komparativ: -er (+ Umlaut bei a/o/u)", "Superlativ: am …-sten", "Different things → als · equal → so … wie", "gut/besser/am besten · gern/lieber/am liebsten · viel/mehr/am meisten"],
    },
  },
];
