import type { ModuleSeed } from "./types";

export const MODULES_A2: ModuleSeed[] = [
  {
    slug: "a2-alltag-routinen",
    title: "Alltag & Routinen",
    description: "Talk about yesterday, handle appointments and survive the doctor's office.",
    icon: "calendar",
    lessons: [
      {
        slug: "a2-gestern-perfekt",
        title: "Was hast du gestern gemacht?",
        subtitle: "The Perfekt in real conversations",
        durationMin: 30,
        objectives: ["Tell what you did yesterday using the Perfekt", "Choose correctly between haben and sein", "Place the Partizip II at the end"],
        blocks: [
          { type: "heading", text: "Endlich über gestern sprechen!" },
          { type: "text", md: "Until now you've lived in the present. The **Perfekt** unlocks the past — and it's how Germans actually talk: *Ich **habe** eingekauft, dann **bin** ich nach Hause **gefahren**.*" },
          { type: "dialogue", title: "Montagmorgen im Büro", lines: [
            { speaker: "Lena", de: "Na, wie war dein Wochenende? Was hast du gemacht?", en: "So, how was your weekend? What did you do?" },
            { speaker: "Omar", de: "Am Samstag habe ich lange geschlafen und dann Freunde getroffen.", en: "On Saturday I slept in and then met friends." },
            { speaker: "Lena", de: "Schön! Seid ihr ausgegangen?", en: "Nice! Did you go out?" },
            { speaker: "Omar", de: "Ja, wir sind in ein marokkanisches Restaurant gegangen. Ich habe zu viel gegessen!", en: "Yes, we went to a Moroccan restaurant. I ate too much!" },
          ] },
          { type: "callout", variant: "grammar", title: "Die Satzklammer", md: "haben/sein sits in **position 2**, the Partizip II at the **very end** — everything else lives in between. *Ich **habe** gestern mit meiner Mutter lange **telefoniert**.* This 'verb bracket' is THE German sentence shape." },
          { type: "exercise", slug: "a2-perfekt-gap" },
          { type: "mistakes", items: [
            { wrong: "Ich habe nach Berlin gefahren.", right: "Ich bin nach Berlin gefahren.", why: "Movement A→B takes sein." },
            { wrong: "Ich habe getroffen meine Freunde.", right: "Ich habe meine Freunde getroffen.", why: "Partizip II at the END — no exceptions." },
          ] },
        ],
        homework: { tasks: ["Write 6 sentences about your last weekend in the Perfekt (mix haben & sein).", "Tell your day out loud tonight — 60 seconds, Perfekt only."] },
      },
      {
        slug: "a2-beim-arzt",
        title: "Beim Arzt",
        subtitle: "Describing symptoms and understanding the doctor",
        durationMin: 25,
        objectives: ["Describe pain and symptoms", "Understand typical doctor questions and instructions", "Handle the Anmeldung at a German practice"],
        blocks: [
          { type: "heading", text: "Was fehlt Ihnen denn?" },
          { type: "dialogue", title: "In der Hausarztpraxis", lines: [
            { speaker: "Ärztin", de: "Guten Tag! Was fehlt Ihnen denn?", en: "Hello! What seems to be the problem?" },
            { speaker: "Omar", de: "Ich habe seit drei Tagen Halsschmerzen und Husten.", en: "I've had a sore throat and cough for three days." },
            { speaker: "Ärztin", de: "Haben Sie auch Fieber?", en: "Do you also have a fever?" },
            { speaker: "Omar", de: "Ja, gestern Abend 38,5.", en: "Yes, 38.5 last night." },
            { speaker: "Ärztin", de: "Das klingt nach einer Erkältung. Ich verschreibe Ihnen etwas gegen den Husten. Bleiben Sie drei Tage zu Hause.", en: "That sounds like a cold. I'll prescribe you something for the cough. Stay home for three days." },
            { speaker: "Omar", de: "Brauche ich eine Krankschreibung für die Arbeit?", en: "Do I need a sick note for work?" },
            { speaker: "Ärztin", de: "Ja, die bekommen Sie vorne an der Anmeldung.", en: "Yes, you'll get that at the front desk." },
          ] },
          { type: "vocab", title: "Symptome & Praxis", words: [
            { de: "Ich habe Kopfschmerzen", en: "I have a headache" }, { de: "die Halsschmerzen", en: "sore throat" },
            { de: "das Fieber", en: "fever" }, { de: "der Husten / der Schnupfen", en: "cough / runny nose" },
            { de: "das Rezept", en: "prescription" }, { de: "die Krankschreibung (AU)", en: "sick note" },
            { de: "die Versichertenkarte", en: "insurance card" }, { de: "Gute Besserung!", en: "get well soon!" },
          ] },
          { type: "callout", variant: "culture", title: "Termin? Immer!", md: "German practices run on appointments — call ahead or use their online booking. Bring your **Versichertenkarte** to every visit. For emergencies outside hours: **116 117** (medical on-call) or **112** (life-threatening)." },
          { type: "exercise", slug: "a2-arzt-mcq" },
        ],
        homework: { tasks: ["Write a 4-line dialogue: you call the practice and describe two symptoms.", "Learn the emergency numbers: 112 and 116 117 — say them in German."] },
      },
      {
        slug: "a2-termine-machen",
        title: "Termine machen",
        subtitle: "Making, moving and cancelling appointments on the phone",
        durationMin: 25,
        objectives: ["Make an appointment on the phone", "Postpone or cancel politely", "Use temporal prepositions am/um/von…bis"],
        blocks: [
          { type: "heading", text: "Deutschland läuft auf Terminen" },
          { type: "dialogue", title: "Anruf beim Friseur", lines: [
            { speaker: "Friseurin", de: "Salon Haarmonie, guten Tag!", en: "Salon Haarmonie, hello!" },
            { speaker: "Lena", de: "Guten Tag, ich hätte gern einen Termin zum Haareschneiden.", en: "Hello, I'd like an appointment for a haircut." },
            { speaker: "Friseurin", de: "Gern. Passt es Ihnen am Donnerstag um 15 Uhr?", en: "Sure. Does Thursday at 3 pm suit you?" },
            { speaker: "Lena", de: "Da kann ich leider nicht. Geht es auch am Freitag?", en: "Unfortunately I can't then. Is Friday possible too?" },
            { speaker: "Friseurin", de: "Ja, Freitag um 14 Uhr ist frei.", en: "Yes, Friday at 2 pm is free." },
            { speaker: "Lena", de: "Perfekt, dann nehme ich den Termin. Vielen Dank!", en: "Perfect, I'll take that appointment. Thanks a lot!" },
          ] },
          { type: "table", title: "Zeit-Präpositionen", headers: ["Präposition", "Verwendung", "Beispiel"], rows: [["am", "Tage & Tageszeiten", "am Montag, am Abend"], ["um", "Uhrzeiten", "um 15 Uhr"], ["im", "Monate & Jahreszeiten", "im Juli, im Winter"], ["von … bis", "Zeitspannen", "von 9 bis 17 Uhr"], ["ab", "Startpunkt", "ab nächster Woche"]] },
          { type: "vocab", title: "Termin-Redemittel", words: [
            { de: "Passt es Ihnen am …?", en: "Does … suit you?" }, { de: "Da kann ich leider nicht.", en: "I can't make it then." },
            { de: "Geht es auch am …?", en: "Would … work too?" }, { de: "den Termin verschieben", en: "to postpone the appointment" },
            { de: "den Termin absagen", en: "to cancel the appointment" }, { de: "Es ist etwas dazwischengekommen.", en: "Something came up." },
          ] },
          { type: "exercise", slug: "a2-termine-gap" },
        ],
        homework: { tasks: ["Roleplay out loud: call and move an appointment from Tuesday to Thursday.", "Write a two-sentence SMS cancelling an appointment politely."] },
      },
    ],
  },
  {
    slug: "a2-stadt-leben",
    title: "Stadt & Leben",
    description: "Directions, shopping for clothes — and your A2 checkpoint.",
    icon: "map-pin",
    lessons: [
      {
        slug: "a2-in-der-stadt",
        title: "Unterwegs in der Stadt",
        subtitle: "Asking for and understanding directions",
        durationMin: 25,
        objectives: ["Ask for directions politely", "Understand typical direction answers", "Use Dativ after mit/zu/bei correctly"],
        blocks: [
          { type: "heading", text: "Entschuldigung, wie komme ich …?" },
          { type: "dialogue", title: "Auf der Straße", lines: [
            { speaker: "Omar", de: "Entschuldigung, wie komme ich zum Hauptbahnhof?", en: "Excuse me, how do I get to the main station?" },
            { speaker: "Passantin", de: "Gehen Sie hier geradeaus bis zur Ampel, dann links.", en: "Go straight ahead to the traffic light, then left." },
            { speaker: "Passantin", de: "Nach 200 Metern sehen Sie den Bahnhof auf der rechten Seite.", en: "After 200 meters you'll see the station on the right side." },
            { speaker: "Omar", de: "Also geradeaus, an der Ampel links. Vielen Dank!", en: "So straight ahead, left at the light. Thank you very much!" },
          ] },
          { type: "callout", variant: "tip", title: "Wiederhole die Antwort!", md: "Locals speak fast. Repeat the route back in keywords — *'Also geradeaus, dann links?'* — you verify AND buy processing time. Real-life listening strategy #1." },
          { type: "vocab", title: "Wegbeschreibung", words: [
            { de: "geradeaus", en: "straight ahead" }, { de: "links / rechts abbiegen", en: "to turn left / right" },
            { de: "die Ampel", en: "traffic light" }, { de: "die Kreuzung", en: "intersection" },
            { de: "gegenüber von", en: "opposite of" }, { de: "in der Nähe", en: "nearby" },
            { de: "zu Fuß", en: "on foot" }, { de: "mit der U-Bahn", en: "by subway" },
          ] },
          { type: "exercise", slug: "a2-dativ-gap" },
        ],
        homework: { tasks: ["Describe the way from your home to the nearest supermarket — 4 sentences, out loud.", "Learn the chunk: 'Wie komme ich zum/zur …?' — zum for der/das, zur for die."] },
      },
      {
        slug: "a2-kleidung-kaufen",
        title: "Kleidung kaufen",
        subtitle: "Clothes, colors, sizes — and saying what fits",
        durationMin: 25,
        objectives: ["Shop for clothes: size, color, price", "Use gefallen and passen with Dativ", "Compare items with Komparativ"],
        blocks: [
          { type: "heading", text: "Im Modegeschäft" },
          { type: "dialogue", title: "Die Jacke", lines: [
            { speaker: "Verkäufer", de: "Kann ich Ihnen helfen?", en: "Can I help you?" },
            { speaker: "Lena", de: "Ja, ich suche eine Winterjacke in Größe M.", en: "Yes, I'm looking for a winter jacket in size M." },
            { speaker: "Verkäufer", de: "Wie gefällt Ihnen diese hier in Blau?", en: "How do you like this one in blue?" },
            { speaker: "Lena", de: "Die ist schön, aber haben Sie sie auch eine Nummer größer?", en: "It's nice, but do you have it one size bigger?" },
            { speaker: "Verkäufer", de: "Moment … hier, Größe L. Die Umkleidekabine ist dort hinten.", en: "One moment… here, size L. The fitting room is back there." },
            { speaker: "Lena", de: "Perfekt, die passt! Die nehme ich.", en: "Perfect, it fits! I'll take it." },
          ] },
          { type: "callout", variant: "grammar", title: "gefallen & passen — mit Dativ!", md: "*Die Jacke gefällt **mir*** (I like the jacket — literally: it pleases me). *Die Hose passt **dir*** (the trousers fit you). The person is always **Dativ**: mir, dir, ihm, ihr, uns, euch, Ihnen." },
          { type: "vocab", title: "Kleidung & Shopping", words: [
            { de: "die Jacke / die Hose / das Hemd", en: "jacket / trousers / shirt" }, { de: "der Pullover / das Kleid", en: "sweater / dress" },
            { de: "die Schuhe", en: "shoes" }, { de: "die Umkleidekabine", en: "fitting room" },
            { de: "Das passt mir (nicht).", en: "It fits me / doesn't fit." }, { de: "eine Nummer größer/kleiner", en: "one size bigger/smaller" },
          ] },
          { type: "exercise", slug: "a2-kleidung-match" },
          { type: "exercise", slug: "a2-komparativ-gap" },
        ],
        homework: { tasks: ["Describe your favorite outfit: colors, why you like it (… gefällt mir, weil …).", "Comparison practice: write 3 sentences comparing two clothing items (billiger, schöner, größer)."] },
      },
      {
        slug: "a2-mini-test",
        title: "Mini-Test A2",
        subtitle: "Perfekt, Dativ, Modalverben — show your progress",
        type: "MINI_TEST",
        durationMin: 20,
        xpReward: 100,
        objectives: ["Test all A2 core structures under real conditions"],
        blocks: [
          { type: "heading", text: "A2-Checkpoint" },
          { type: "text", md: "No notes, no dictionary — just you and everything you've learned since A1. 80%+ means you're ready for B1's subordinate clauses. Los! 💪" },
          { type: "exercise", slug: "a2-modalverben-mcq" },
          { type: "exercise", slug: "a2-trennbare-ordnen" },
          { type: "exercise", slug: "a2-test-mix" },
          { type: "callout", variant: "info", title: "Nächster Schritt", md: "Solid score? Try the **TELC A2 mock exam** for the full timed experience — then B1 awaits, where your German starts sounding genuinely connected." },
        ],
      },
    ],
  },
];

export const MODULES_B1: ModuleSeed[] = [
  {
    slug: "b1-meine-meinung",
    title: "Meine Meinung",
    description: "Opinions, media and the environment — start arguing (politely) in German.",
    icon: "message-circle",
    lessons: [
      {
        slug: "b1-meinung-aeussern",
        title: "Meiner Meinung nach …",
        subtitle: "Stating opinions with weil, dass and Redemittel",
        durationMin: 30,
        objectives: ["State and justify opinions with fixed phrases", "Build weil/dass clauses with the verb at the end", "Politely agree and disagree"],
        blocks: [
          { type: "heading", text: "Vom Small Talk zur Diskussion" },
          { type: "text", md: "B1 is where German gets interesting: you stop naming things and start **arguing positions**. The engine: opinion phrase + **weil**-clause with the verb at the end." },
          { type: "table", title: "Redemittel: Meinung", headers: ["Funktion", "Redemittel"], rows: [["Meinung äußern", "Meiner Meinung nach … / Ich finde, dass … / Ich bin der Meinung, dass …"], ["Zustimmen", "Da stimme ich dir zu. / Genau! / Das sehe ich auch so."], ["Widersprechen", "Das sehe ich anders. / Da bin ich anderer Meinung. / Schon, aber …"], ["Begründen", "…, weil … / …, denn … / Deshalb …"]] },
          { type: "dialogue", title: "Diskussion: Homeoffice", lines: [
            { speaker: "Lena", de: "Ich finde, dass Homeoffice viele Vorteile hat.", en: "I think working from home has many advantages." },
            { speaker: "Omar", de: "Da stimme ich dir zu, weil man keine Zeit im Verkehr verliert.", en: "I agree, because you don't lose time in traffic." },
            { speaker: "Lena", de: "Genau! Aber meine Kollegin sagt, dass ihr der Kontakt zu den Leuten fehlt.", en: "Exactly! But my colleague says she misses contact with people." },
            { speaker: "Omar", de: "Das verstehe ich. Deshalb ist eine Mischung wahrscheinlich am besten.", en: "I understand that. That's why a mix is probably best." },
          ] },
          { type: "exercise", slug: "b1-nebensaetze-ordnen" },
          { type: "callout", variant: "tip", title: "Die B1-Prüfungsformel", md: "For any discussion topic: **These + weil-Begründung + Beispiel + Gegenseite (einerseits/andererseits) + Fazit.** Practice it until it's automatic — it carries the entire mündliche Prüfung." },
        ],
        homework: { tasks: ["Pick a topic (city vs. countryside) and write 5 sentences using the exam formula.", "Record yourself giving your opinion for 60 seconds — count your weil-clauses."] },
      },
      {
        slug: "b1-medienkonsum",
        title: "Medien im Alltag",
        subtitle: "Talking about phones, news and screen time",
        durationMin: 25,
        objectives: ["Discuss media habits with statistics", "Use Vorteil/Nachteil structures", "Understand a short opinion text"],
        blocks: [
          { type: "heading", text: "Immer online?" },
          { type: "text", md: "**Lies den Kurztext:**\n\nLaut einer Studie schauen junge Erwachsene in Deutschland im Durchschnitt mehr als drei Stunden pro Tag auf ihr Handy. Einerseits machen Apps den Alltag leichter: Man kann Tickets kaufen, mit der Familie sprechen und Nachrichten lesen. Andererseits sagen viele, dass sie sich schlechter konzentrieren können und abends schlecht einschlafen. Immer mehr Menschen machen deshalb einen „Digital Detox\" — einen Tag pro Woche ganz ohne Smartphone." },
          { type: "examples", title: "Über Statistiken sprechen", items: [
            { de: "Laut einer Studie verbringen wir drei Stunden am Handy.", en: "According to a study, we spend three hours on the phone.", note: "laut + Dativ" },
            { de: "Im Durchschnitt sind es bei mir eher vier …", en: "On average it's more like four for me…" },
            { de: "Die Zahl der Nutzer ist gestiegen.", en: "The number of users has risen." },
          ] },
          { type: "callout", variant: "grammar", title: "einerseits … andererseits", md: "The elegant pro/contra structure: *Einerseits **machen** Apps den Alltag leichter, andererseits **verlieren** wir viel Zeit.* Both are main clauses — verb in position 2 after each!" },
          { type: "exercise", slug: "b1-medien-mcq" },
        ],
        homework: { tasks: ["Write your own einerseits/andererseits paragraph about social media (4-6 sentences).", "Check your real screen time and say the number out loud in German."] },
      },
      {
        slug: "b1-umwelt-alltag",
        title: "Umwelt im Alltag",
        subtitle: "Sustainability talk — Germany's favorite topic",
        durationMin: 25,
        objectives: ["Discuss everyday environmental choices", "Make suggestions with sollte and könnte", "Master the Mülltrennung vocabulary"],
        blocks: [
          { type: "heading", text: "Klimaschutz beginnt in der Küche" },
          { type: "dialogue", title: "In der WG-Küche", lines: [
            { speaker: "Mia", de: "Omar, die Plastikflasche kommt nicht in den Restmüll!", en: "Omar, the plastic bottle doesn't go in the general waste!" },
            { speaker: "Omar", de: "Oh, sorry! Wohin denn dann?", en: "Oh, sorry! Where does it go then?" },
            { speaker: "Mia", de: "In die gelbe Tonne. Und die Flasche hat sogar Pfand — die bringst du besser zum Supermarkt.", en: "In the yellow bin. And the bottle even has a deposit — better take it to the supermarket." },
            { speaker: "Omar", de: "Deutschland und sein Müllsystem … Aber ehrlich: Ich finde es eigentlich gut.", en: "Germany and its waste system… But honestly: I actually think it's good." },
          ] },
          { type: "table", title: "Mülltrennung — der Crashkurs", headers: ["Tonne", "Farbe", "Was rein kommt"], rows: [["Papiertonne", "blau", "Papier, Kartons"], ["Gelbe Tonne", "gelb", "Plastik, Verpackungen"], ["Biotonne", "braun", "Essensreste, Bio-Abfall"], ["Restmüll", "schwarz/grau", "der Rest"], ["Glascontainer", "—", "Glas nach Farben!"]] },
          { type: "examples", title: "Vorschläge machen", items: [
            { de: "Wir sollten weniger Plastik kaufen.", en: "We should buy less plastic." },
            { de: "Man könnte öfter mit dem Rad fahren.", en: "One could cycle more often." },
            { de: "Es wäre besser, regionale Produkte zu kaufen.", en: "It would be better to buy regional products." },
          ] },
          { type: "exercise", slug: "b1-umwelt-gap" },
        ],
        homework: { tasks: ["Write 5 suggestions for your household with sollte/könnte.", "Name (in German) what goes in each of the four bins — out loud, 30 seconds."] },
      },
    ],
  },
  {
    slug: "b1-arbeit-traeume",
    title: "Arbeit & Träume",
    description: "Work life, telling stories about travel — and your B1 checkpoint.",
    icon: "briefcase",
    lessons: [
      {
        slug: "b1-arbeitswelt",
        title: "Die Arbeitswelt",
        subtitle: "Jobs, Präteritum and telling your professional story",
        durationMin: 30,
        objectives: ["Describe your work history with Präteritum and Perfekt", "Use job-world vocabulary confidently", "Understand a short formal email"],
        blocks: [
          { type: "heading", text: "Dein beruflicher Weg" },
          { type: "text", md: "Interviews, small talk, forms — everyone asks about your **Werdegang**. Pattern: **Präteritum** for war/hatte + background, **Perfekt** for events: *Ich **war** drei Jahre Verkäufer und **habe** dann eine Ausbildung **angefangen**.*" },
          { type: "examples", title: "So erzählst du deinen Weg", items: [
            { de: "Von 2019 bis 2022 habe ich als Kellner gearbeitet.", en: "From 2019 to 2022 I worked as a waiter." },
            { de: "Damals hatte ich wenig Zeit, aber ich wollte unbedingt Deutsch lernen.", en: "Back then I had little time, but I really wanted to learn German." },
            { de: "Deshalb habe ich einen Abendkurs gemacht.", en: "That's why I took an evening course." },
          ] },
          { type: "text", md: "**Lies die E-Mail:**\n\nSehr geehrter Herr El Amrani,\n\nvielen Dank für Ihre Bewerbung. Wir möchten Sie gern persönlich kennenlernen und laden Sie zu einem Gespräch am Dienstag, den 14. März um 10:00 Uhr ein. Bitte bringen Sie Ihre Zeugnisse mit.\n\nMit freundlichen Grüßen\nSandra Weber, Personalabteilung" },
          { type: "callout", variant: "tip", title: "Formelle E-Mails lesen", md: "Scan for the skeleton: **Wer?** (Personalabteilung) **Was?** (Einladung zum Gespräch) **Wann?** (Di, 14.3., 10 Uhr) **Was mitbringen?** (Zeugnisse). Four questions decode any formal mail." },
          { type: "exercise", slug: "b1-praeteritum-gap" },
        ],
        homework: { tasks: ["Write your Werdegang in 6 sentences (mix Präteritum for war/hatte/wollte with Perfekt).", "Reply to the invitation email in 3 polite sentences: confirm and thank."] },
      },
      {
        slug: "b1-reisen-erzaehlen",
        title: "Von Reisen erzählen",
        subtitle: "Travel stories with connectors that flow",
        durationMin: 25,
        objectives: ["Tell a travel story in chronological order", "Connect sentences with zuerst/danach/schließlich", "Use als for past events"],
        blocks: [
          { type: "heading", text: "Die Kunst des Erzählens" },
          { type: "text", md: "A story is just events + **connectors**: *zuerst → dann → danach → später → schließlich → am Ende*. Add one **als**-clause and one opinion, and you have a perfect B1 mündliche Präsentation." },
          { type: "dialogue", title: "Erzähl mal!", lines: [
            { speaker: "Lena", de: "Du warst in Portugal? Erzähl mal!", en: "You were in Portugal? Tell me about it!" },
            { speaker: "Omar", de: "Also, zuerst sind wir zwei Tage in Lissabon geblieben. Die Stadt hat mir super gefallen.", en: "So, first we stayed two days in Lisbon. I really loved the city." },
            { speaker: "Omar", de: "Danach haben wir ein Auto gemietet und sind an die Küste gefahren.", en: "After that we rented a car and drove to the coast." },
            { speaker: "Omar", de: "Als wir in Porto ankamen, hat es leider geregnet — aber der Wein war fantastisch!", en: "When we arrived in Porto, it unfortunately rained — but the wine was fantastic!" },
            { speaker: "Lena", de: "Klingt traumhaft. Würdest du wieder hinfahren?", en: "Sounds dreamy. Would you go again?" },
            { speaker: "Omar", de: "Sofort! Nächstes Mal bleibe ich aber länger.", en: "Immediately! But next time I'll stay longer." },
          ] },
          { type: "callout", variant: "grammar", title: "als vs. wenn — die Kurzversion", md: "**als** = one single time in the past (*Als ich in Porto ankam…*). **wenn** = repeated events or present/future (*Wenn ich reise, …*). Exams love this distinction." },
          { type: "exercise", slug: "b1-reisen-ordnen" },
        ],
        homework: { tasks: ["Tell your best trip in 8 sentences using at least 4 connectors and one als-clause.", "Record it — 90 seconds. Listen once. Record again better."] },
      },
      {
        slug: "b1-mini-test",
        title: "Mini-Test B1",
        subtitle: "Nebensätze, cases and adjectives — the B1 gate",
        type: "MINI_TEST",
        durationMin: 20,
        xpReward: 100,
        objectives: ["Test all B1 core structures"],
        blocks: [
          { type: "heading", text: "B1-Checkpoint" },
          { type: "text", md: "The structures in this test — subordinate clauses, two-way prepositions, adjective endings — are exactly what separates B1 from A2 in every official exam. Kein Stress, zeig einfach, was du kannst." },
          { type: "exercise", slug: "b1-wechselpraep-mcq" },
          { type: "exercise", slug: "b1-adjektive-gap" },
          { type: "exercise", slug: "b1-test-mix" },
          { type: "callout", variant: "info", title: "Der große Moment", md: "B1 is THE certificate level (citizenship, many jobs). Take the **Goethe B1 mock exam** now — full length, real timing. You're readier than you think." },
        ],
      },
    ],
  },
];

export const MODULES_B2: ModuleSeed[] = [
  {
    slug: "b2-sprache-stil",
    title: "Sprache & Stil",
    description: "Passive voice, diplomatic language and presenting like a pro.",
    icon: "book-open",
    lessons: [
      {
        slug: "b2-passiv-beruf",
        title: "Passiv im Beruf",
        subtitle: "Process descriptions and professional writing",
        durationMin: 30,
        objectives: ["Describe processes with the Vorgangspassiv", "Use Passiv with modal verbs", "Recognize when passive beats active"],
        blocks: [
          { type: "heading", text: "Wenn der Prozess wichtiger ist als die Person" },
          { type: "text", md: "Professional German runs on passive: instructions, reports, official letters. *Die Bestellung **wird** innerhalb von 24 Stunden **bearbeitet**.* Nobody cares WHO processes it — the process is the point." },
          { type: "examples", title: "Typische Beruf-Passive", items: [
            { de: "Die Ware wird am Montag geliefert.", en: "The goods will be delivered on Monday." },
            { de: "Das Meeting wurde auf Freitag verschoben.", en: "The meeting was moved to Friday." },
            { de: "Alle Daten müssen gespeichert werden.", en: "All data must be saved.", note: "Modal + P2 + werden" },
            { de: "Hier wird Deutsch gesprochen.", en: "German is spoken here." },
          ] },
          { type: "callout", variant: "tip", title: "Aktiv oder Passiv — die Stilfrage", md: "Passive when the actor is unknown/unimportant/obvious. Active when a person matters. Emails mix both: *Ihre Anfrage **wurde weitergeleitet**. Ich **melde mich** morgen bei Ihnen.*" },
          { type: "exercise", slug: "b2-passiv-gap" },
          { type: "mistakes", items: [
            { wrong: "Der Report wird geschreibt.", right: "Der Report wird geschrieben.", why: "Passive needs the real Partizip II — schreiben is irregular: geschrieben." },
            { wrong: "Das Problem ist gelöst worden von mir.", right: "Das Problem ist von mir gelöst worden. (besser: Ich habe das Problem gelöst.)", why: "von-phrase goes inside the bracket — or just use active when YOU matter." },
          ] },
        ],
        homework: { tasks: ["Describe in 5 passive sentences how a pizza gets to a customer (bestellt, gebacken, geliefert …).", "Find 3 passive sentences in any German news article and translate them."] },
      },
      {
        slug: "b2-diplomatisch",
        title: "Die Kunst der Höflichkeit",
        subtitle: "Konjunktiv II for requests, suggestions and soft criticism",
        durationMin: 30,
        objectives: ["Make diplomatic requests with Konjunktiv II", "Soften criticism professionally", "Handle difficult conversations politely"],
        blocks: [
          { type: "heading", text: "Sag es — aber elegant" },
          { type: "text", md: "B2 German is diplomatic German. The difference between *Das ist falsch* and *Da **wäre** ich mir nicht so sicher* can decide how a meeting ends. Your tool: **Konjunktiv II**." },
          { type: "table", title: "Direkt → Diplomatisch", headers: ["Direkt 😬", "Diplomatisch 😊"], rows: [["Das ist falsch.", "Ich bin nicht sicher, ob das so stimmt."], ["Machen Sie das neu!", "Könnten Sie das noch einmal überarbeiten?"], ["Ich will eine Antwort bis Freitag.", "Ich wäre Ihnen dankbar, wenn Sie bis Freitag antworten könnten."], ["Ihr Plan funktioniert nicht.", "Der Plan hätte meiner Meinung nach zwei Schwachstellen."]] },
          { type: "dialogue", title: "Feedback-Gespräch", lines: [
            { speaker: "Chefin", de: "Herr El Amrani, hätten Sie kurz Zeit? Es geht um den Bericht.", en: "Mr. El Amrani, would you have a moment? It's about the report." },
            { speaker: "Omar", de: "Natürlich. Gibt es ein Problem?", en: "Of course. Is there a problem?" },
            { speaker: "Chefin", de: "Kein Problem — aber es wäre gut, wenn die Zahlen aktueller wären. Könnten Sie das bis Donnerstag anpassen?", en: "No problem — but it would be good if the figures were more current. Could you adjust that by Thursday?" },
            { speaker: "Omar", de: "Selbstverständlich. Ich würde vorschlagen, dass ich Ihnen morgen eine erste Version schicke.", en: "Of course. I'd suggest I send you a first version tomorrow." },
          ] },
          { type: "exercise", slug: "b2-konjunktiv-gap" },
        ],
        homework: { tasks: ["Rewrite these diplomatically: 'Das Meeting ist unnötig.' / 'Antworten Sie schneller!' / 'Ihre Idee ist zu teuer.'", "Write a 4-sentence email asking your landlord (diplomatically!) to finally fix the heating."] },
      },
      {
        slug: "b2-praesentieren",
        title: "Präsentieren auf Deutsch",
        subtitle: "Structure, signal phrases and handling questions",
        durationMin: 30,
        objectives: ["Structure a presentation with German signal phrases", "Present a topic for 3+ minutes", "React to questions confidently"],
        blocks: [
          { type: "heading", text: "Der 3-Minuten-Vortrag" },
          { type: "text", md: "The B2 speaking exam and every meeting share one skeleton. Memorize the signal phrases as furniture — then you only think about content, never about form." },
          { type: "table", title: "Vortrags-Bausteine", headers: ["Phase", "Signalphrasen"], rows: [["Einstieg", "Heute möchte ich über … sprechen. / Mein Thema ist …"], ["Gliederung", "Zuerst …, dann …, zum Schluss …"], ["Übergang", "Kommen wir nun zu … / Ein weiterer Punkt ist …"], ["Beispiel", "Ein gutes Beispiel dafür ist … / Aus eigener Erfahrung …"], ["Meinung", "Ich persönlich bin überzeugt, dass …"], ["Schluss", "Zusammenfassend lässt sich sagen, dass … / Vielen Dank für Ihre Aufmerksamkeit!"]] },
          { type: "callout", variant: "tip", title: "Auf Fragen reagieren", md: "- Verstanden? *Gute Frage! Ich denke, dass …*\n- Nicht verstanden? *Könnten Sie die Frage bitte wiederholen?*\n- Keine Ahnung? *Das kann ich aus dem Stegreif nicht sagen, aber ich vermute …* — honest AND fluent." },
          { type: "exercise", slug: "b2-vortrag-match" },
          { type: "text", md: "**Deine Aufgabe:** Bereite mit den Bausteinen einen 3-Minuten-Vortrag vor: *Sollte man ein Jahr im Ausland leben?* — Einstieg, zwei Argumente mit Beispielen, deine Meinung, Schluss. Nutze den Recorder auf der Speaking-Seite!" },
        ],
        homework: { tasks: ["Hold your 3-minute presentation out loud and record it.", "Listen back and count your signal phrases — target: at least 5."] },
      },
    ],
  },
  {
    slug: "b2-beruf-gesellschaft",
    title: "Beruf & Gesellschaft",
    description: "Applications, debate — and the final B2 checkpoint.",
    icon: "landmark",
    lessons: [
      {
        slug: "b2-bewerbung",
        title: "Die perfekte Bewerbung",
        subtitle: "Anschreiben language that gets interviews",
        durationMin: 30,
        objectives: ["Write a convincing Anschreiben paragraph", "Use Nomen-Verb-Verbindungen in applications", "Avoid the classic application clichés"],
        blocks: [
          { type: "heading", text: "90 Sekunden Aufmerksamkeit" },
          { type: "text", md: "Recruiters skim. Your Anschreiben has ~90 seconds to say: **Ich kann das** (skills + proof), **ich will das** (motivation), **ich passe zu Ihnen** (company fit). Every sentence serves one of the three." },
          { type: "examples", title: "Schwach → Stark", items: [
            { de: "Hiermit bewerbe ich mich um … → Mit großem Interesse habe ich Ihre Ausschreibung gelesen, denn …", en: "Skip the robotic opener — start with genuine interest + reason." },
            { de: "Ich bin teamfähig. → Im Projekt X habe ich mit fünf Kollegen die Lieferzeiten um 20 % verkürzt.", en: "Claims are cheap — evidence wins." },
            { de: "Ich hoffe, von Ihnen zu hören. → Über die Einladung zu einem persönlichen Gespräch freue ich mich sehr.", en: "End confident, not hopeful." },
          ] },
          { type: "callout", variant: "grammar", title: "Bewerbungs-Deutsch = Nomen-Verb-Verbindungen", md: "*Verantwortung **übernehmen**, Erfahrungen **sammeln**, zur Verfügung **stehen**, einen Beitrag **leisten*** — these fixed pairings are the sound of professional German. Sprinkle 2-3 into any application." },
          { type: "exercise", slug: "b2-bewerbung-gap" },
          { type: "callout", variant: "info", title: "Weiter üben", md: "The complete templates (Lebenslauf + Anschreiben) with examples live in the **Ausbildung section** — and the Writing area has a full B2 application task with AI feedback." },
        ],
        homework: { tasks: ["Write your strongest 3-sentence 'Warum ich?' paragraph for a real job you'd want.", "Upgrade it with two Nomen-Verb-Verbindungen."] },
      },
      {
        slug: "b2-debattieren",
        title: "Debattieren",
        subtitle: "Argue both sides — with Relativsätze for precision",
        durationMin: 30,
        objectives: ["Argue pro and contra positions fluently", "Use relative clauses for precise definitions", "Concede points without losing the debate"],
        blocks: [
          { type: "heading", text: "Die hohe Schule: beide Seiten" },
          { type: "text", md: "B2 exams love making you argue a side you didn't choose. The skill: **concede + counter**. *Es stimmt zwar, dass …, aber man darf nicht vergessen, dass …*" },
          { type: "table", title: "Debatten-Redemittel", headers: ["Funktion", "Phrase"], rows: [["Position beziehen", "Ich vertrete den Standpunkt, dass …"], ["Zugeständnis", "Es stimmt zwar, dass …, aber …"], ["Kontern", "Dem möchte ich widersprechen, denn …"], ["Präzisieren", "Menschen, die täglich pendeln, wissen, dass …"], ["Abschließen", "Alles in allem überwiegen für mich die Vorteile."]] },
          { type: "dialogue", title: "Streitgespräch: Autofreie Innenstadt", lines: [
            { speaker: "Pro", de: "Ich vertrete den Standpunkt, dass Innenstädte autofrei werden sollten — die Luft, die wir atmen, wäre sofort besser.", en: "I take the position that city centers should become car-free — the air we breathe would immediately be better." },
            { speaker: "Contra", de: "Es stimmt zwar, dass die Luft besser wäre. Aber was ist mit Menschen, die schlecht zu Fuß sind?", en: "It's true the air would be better. But what about people who have difficulty walking?" },
            { speaker: "Pro", de: "Ein Argument, das ich ernst nehme — deshalb bräuchte man mehr Busse, die alle Viertel verbinden.", en: "An argument I take seriously — that's why you'd need more buses connecting all districts." },
            { speaker: "Contra", de: "Und die Geschäfte, deren Kunden mit dem Auto kommen? Alles in allem sehe ich mehr Risiken.", en: "And the shops whose customers come by car? All in all I see more risks." },
          ] },
          { type: "exercise", slug: "b2-relativ-mcq" },
        ],
        homework: { tasks: ["Pick a debate topic and write 3 concede+counter exchanges (both voices — you play both sides).", "Note 2 relative clauses from the dialogue and build 2 of your own."] },
      },
      {
        slug: "b2-mini-test",
        title: "Mini-Test B2",
        subtitle: "The final checkpoint — Passiv, Konjunktiv, NVV",
        type: "MINI_TEST",
        durationMin: 20,
        xpReward: 100,
        objectives: ["Test all B2 core structures"],
        blocks: [
          { type: "heading", text: "Der letzte Checkpoint" },
          { type: "text", md: "From 'Hallo, ich bin …' to Passiv and diplomatic Konjunktiv — this test closes the loop. Take a breath. You've earned this level." },
          { type: "exercise", slug: "b2-nvv-match" },
          { type: "exercise", slug: "b2-test-mix" },
          { type: "callout", variant: "info", title: "Das Finale", md: "Now the real thing: the **TELC B2 mock exam** — full length, timed, scored. Pass it and your Deutschwerk B2 certificate is waiting. Danach? Die Welt. 🌍" },
        ],
      },
    ],
  },
];
