import type { ModuleSeed } from "./types";

export const MODULES_A1: ModuleSeed[] = [
  {
    slug: "a1-erste-schritte",
    title: "Erste Schritte",
    description: "Say hello, introduce yourself and survive your first German conversation.",
    icon: "hand",
    lessons: [
      {
        slug: "a1-hallo-ich-bin",
        title: "Hallo! Ich bin …",
        subtitle: "Greetings and introducing yourself",
        durationMin: 20,
        objectives: ["Greet people formally and informally", "Introduce yourself with name and origin", "Use sein with ich, du and Sie"],
        blocks: [
          { type: "heading", text: "Dein erstes Gespräch" },
          { type: "text", md: "Welcome to German! In this first lesson you'll learn to say hello, tell people who you are and ask the same back. That's already enough for a real conversation — **los geht's!**" },
          { type: "dialogue", title: "Im Sprachkurs", lines: [
            { speaker: "Lena", de: "Hallo! Ich bin Lena. Und wer bist du?", en: "Hello! I'm Lena. And who are you?" },
            { speaker: "Omar", de: "Hallo Lena! Ich bin Omar. Ich komme aus Marokko.", en: "Hello Lena! I'm Omar. I come from Morocco." },
            { speaker: "Lena", de: "Schön! Ich komme aus Deutschland, aus Köln.", en: "Nice! I come from Germany, from Cologne." },
            { speaker: "Omar", de: "Freut mich!", en: "Nice to meet you!" },
          ] },
          { type: "heading", text: "Formell oder informell?" },
          { type: "table", title: "Zwei Register", headers: ["Situation", "informell (du)", "formell (Sie)"], rows: [["Begrüßung", "Hallo! / Hi!", "Guten Tag!"], ["Name erfragen", "Wie heißt du?", "Wie heißen Sie?"], ["Herkunft", "Woher kommst du?", "Woher kommen Sie?"], ["Verabschiedung", "Tschüss!", "Auf Wiedersehen!"]] },
          { type: "callout", variant: "culture", title: "Wann sagt man du?", md: "Among students, friends and online: **du**. With officials, in shops, at the doctor, with strangers over ~16: **Sie** — until they offer the du. When unsure, start with Sie; nobody is ever offended by politeness." },
          { type: "vocab", title: "Wortschatz der Lektion", words: [
            { de: "Hallo", en: "hello" }, { de: "Guten Tag", en: "good day (formal hello)" }, { de: "Ich bin …", en: "I am …" },
            { de: "Ich heiße …", en: "My name is …" }, { de: "Ich komme aus …", en: "I come from …" }, { de: "Freut mich!", en: "Nice to meet you!" },
            { de: "Tschüss", en: "bye" }, { de: "Auf Wiedersehen", en: "goodbye (formal)" },
          ] },
          { type: "exercise", slug: "a1-hallo-mcq" },
          { type: "callout", variant: "tip", title: "Sprich sofort!", md: "Say the dialogue **out loud** three times — once as Lena, once as Omar, once with your own name and country. Speaking from day one is the single biggest accelerator." },
        ],
        homework: { tasks: ["Introduce yourself out loud in front of a mirror: name, origin, one greeting, one goodbye.", "Write your own 4-line dialogue like the one above with your real name and city.", "Add the lesson vocabulary to your flashcard deck."] },
      },
      {
        slug: "a1-woher-kommst-du",
        title: "Woher kommst du?",
        subtitle: "Countries, languages and the verb kommen",
        durationMin: 25,
        objectives: ["Ask and answer where someone is from", "Name common countries and languages", "Conjugate kommen, wohnen and sprechen (ich/du/er)"],
        blocks: [
          { type: "heading", text: "Länder und Sprachen" },
          { type: "text", md: "Three little questions carry every first conversation: **Woher kommst du?** (origin), **Wo wohnst du?** (home) and **Welche Sprachen sprichst du?** (languages)." },
          { type: "table", title: "Land → Sprache", headers: ["Land", "Sprache", "Beispielsatz"], rows: [["Deutschland", "Deutsch", "Ich spreche Deutsch."], ["Marokko", "Arabisch", "Ich komme aus Marokko."], ["Frankreich", "Französisch", "Er spricht Französisch."], ["die Türkei ⚠️", "Türkisch", "Sie kommt aus der Türkei."], ["Spanien", "Spanisch", "Wir sprechen Spanisch."]], caption: "⚠️ A few countries take an article: die Türkei, die Schweiz, die USA — aus DER Türkei." },
          { type: "examples", title: "Das Muster", items: [
            { de: "Ich komme aus Italien, aber ich wohne in Berlin.", en: "I come from Italy, but I live in Berlin." },
            { de: "Woher kommen Sie?", en: "Where do you come from? (formal)" },
            { de: "Sie spricht Englisch, Arabisch und ein bisschen Deutsch.", en: "She speaks English, Arabic and a little German." },
          ] },
          { type: "callout", variant: "grammar", title: "sprechen wechselt den Vokal", md: "sprechen is irregular: ich spreche, **du sprichst, er/sie spricht** — the e becomes i in du/er forms. You'll meet this pattern again (essen → isst, sehen → sieht)." },
          { type: "exercise", slug: "a1-laender-gap" },
          { type: "mistakes", items: [
            { wrong: "Ich komme von Marokko.", right: "Ich komme aus Marokko.", why: "Countries and cities take aus, not von." },
            { wrong: "Ich spreche Deutsch ein bisschen.", right: "Ich spreche ein bisschen Deutsch.", why: "'ein bisschen' goes before the language." },
          ] },
        ],
        homework: { tasks: ["Write 5 sentences about people you know: name, country, city, language(s).", "Look up 3 more countries + languages you care about and add them to your notes."] },
      },
      {
        slug: "a1-zahlen-alphabet",
        title: "Zahlen & Alphabet",
        subtitle: "Counting to 100 and spelling your name",
        durationMin: 25,
        objectives: ["Count from 0 to 100", "Understand the reversed two-digit numbers", "Spell your name with the German alphabet"],
        blocks: [
          { type: "heading", text: "Die Zahlen 0–20" },
          { type: "table", headers: ["0–10", "11–20"], rows: [["null, eins, zwei, drei, vier, fünf", "elf, zwölf, dreizehn, vierzehn, fünfzehn"], ["sechs, sieben, acht, neun, zehn", "sechzehn, siebzehn, achtzehn, neunzehn, zwanzig"]], caption: "Watch out: sechzehn (not sechszehn), siebzehn (not siebenzehn)." },
          { type: "callout", variant: "warning", title: "Deutsch zählt rückwärts!", md: "Two-digit numbers are said **units first**: 21 = **einundzwanzig** (one-and-twenty), 45 = **fünfundvierzig**, 99 = **neunundneunzig**. Train your ear — this trips up everyone at first." },
          { type: "examples", title: "Zahlen im Alltag", items: [
            { de: "Meine Telefonnummer ist null-eins-sieben-sechs …", en: "My phone number is 0176…" },
            { de: "Das kostet dreiundzwanzig Euro fünfzig.", en: "That costs 23.50 euros." },
            { de: "Ich bin achtundzwanzig Jahre alt.", en: "I'm 28 years old." },
          ] },
          { type: "heading", text: "Buchstabieren" },
          { type: "text", md: "You WILL be asked to spell your name in Germany — at the Bürgeramt, the doctor, on the phone. Practice with the alphabet in the **Pronunciation Studio**, and remember the German specials: **ä, ö, ü** and **ß** (Eszett)." },
          { type: "dialogue", title: "Am Telefon", lines: [
            { speaker: "Beamtin", de: "Wie ist Ihr Name, bitte?", en: "What is your name, please?" },
            { speaker: "Omar", de: "Omar El Amrani. Ich buchstabiere: E-L, neues Wort, A-M-R-A-N-I.", en: "Omar El Amrani. I'll spell it: E-L, new word, A-M-R-A-N-I." },
            { speaker: "Beamtin", de: "Danke schön. Und Ihre Telefonnummer?", en: "Thank you. And your phone number?" },
            { speaker: "Omar", de: "Null-eins-fünf-zwei, drei-vier-acht-neun-null-eins.", en: "0152 348901." },
          ] },
          { type: "exercise", slug: "a1-zahlen-match" },
        ],
        homework: { tasks: ["Say your phone number out loud in German — digit by digit, then in pairs.", "Count down from 30 to 0 while making coffee.", "Spell your full name out loud twice."] },
      },
    ],
  },
  {
    slug: "a1-meine-welt",
    title: "Meine Welt",
    description: "Family, food and your daily routine — talking about the life you actually live.",
    icon: "heart",
    lessons: [
      {
        slug: "a1-meine-familie",
        title: "Meine Familie",
        subtitle: "Family members and possessives mein/dein",
        durationMin: 25,
        objectives: ["Name family members with the right article", "Use mein/meine and dein/deine correctly", "Say how old someone is"],
        blocks: [
          { type: "heading", text: "Wer gehört zur Familie?" },
          { type: "text", md: "Time to talk about your people. Notice how the possessive **mein** works exactly like **ein**: *mein Bruder* (der), *meine Schwester* (die), *mein Kind* (das)." },
          { type: "table", title: "mein & dein", headers: ["", "maskulin", "feminin", "neutral", "Plural"], rows: [["mein", "mein Vater", "meine Mutter", "mein Kind", "meine Eltern"], ["dein", "dein Bruder", "deine Schwester", "dein Baby", "deine Geschwister"]] },
          { type: "dialogue", title: "Fotos zeigen", lines: [
            { speaker: "Anna", de: "Ist das deine Familie auf dem Foto?", en: "Is that your family in the photo?" },
            { speaker: "Omar", de: "Ja! Das ist meine Mutter, und das hier ist mein Bruder Karim.", en: "Yes! That's my mother, and this here is my brother Karim." },
            { speaker: "Anna", de: "Wie alt ist dein Bruder?", en: "How old is your brother?" },
            { speaker: "Omar", de: "Er ist neunzehn. Und er spricht schon gut Deutsch!", en: "He's nineteen. And he already speaks German well!" },
          ] },
          { type: "vocab", title: "Die Familie", words: [
            { de: "die Eltern", en: "parents" }, { de: "die Mutter / der Vater", en: "mother / father" },
            { de: "der Bruder / die Schwester", en: "brother / sister" }, { de: "die Geschwister", en: "siblings" },
            { de: "die Großeltern", en: "grandparents" }, { de: "der Sohn / die Tochter", en: "son / daughter" },
            { de: "verheiratet", en: "married" }, { de: "ledig", en: "single" },
          ] },
          { type: "exercise", slug: "a1-familie-match" },
          { type: "callout", variant: "tip", title: "Merkhilfe", md: "**mein/dein = ein with an m/d in front.** If you know 'ein Bruder', you automatically know 'mein Bruder' and 'kein Bruder'. Three words for the price of one!" },
        ],
        homework: { tasks: ["Draw a mini family tree and label everyone in German with articles.", "Write 5 sentences: Das ist mein(e) … Er/Sie ist … Jahre alt.", "Add the family words to your flashcard deck."] },
      },
      {
        slug: "a1-im-cafe",
        title: "Im Café",
        subtitle: "Ordering food and drinks politely",
        durationMin: 25,
        objectives: ["Order food and drinks with ich möchte / ich hätte gern", "Ask for the bill", "Understand prices"],
        blocks: [
          { type: "heading", text: "Bestellen wie ein Profi" },
          { type: "text", md: "Your first real-world victory: ordering in German. The magic phrase is **Ich hätte gern …** (I'd like…) — polite, natural, and it works for everything from coffee to train tickets." },
          { type: "dialogue", title: "Im Café Sonnenschein", lines: [
            { speaker: "Kellner", de: "Guten Tag! Was darf es sein?", en: "Good day! What can I get you?" },
            { speaker: "Lena", de: "Ich hätte gern einen Cappuccino, bitte.", en: "I'd like a cappuccino, please." },
            { speaker: "Omar", de: "Und für mich einen Tee und ein Käsebrötchen.", en: "And for me a tea and a cheese roll." },
            { speaker: "Kellner", de: "Gern. Kommt sofort!", en: "Gladly. Coming right up!" },
            { speaker: "Omar", de: "Wir möchten bitte zahlen. Zusammen, bitte.", en: "We'd like to pay, please. Together, please." },
            { speaker: "Kellner", de: "Das macht sieben Euro achtzig.", en: "That's 7.80 euros." },
          ] },
          { type: "callout", variant: "culture", title: "Zusammen oder getrennt?", md: "German servers always ask: **Zusammen oder getrennt?** (together or separately?) — splitting the bill precisely is completely normal. Tipping: round up 5–10%, say the total as you pay: *'Neun Euro, bitte'*." },
          { type: "vocab", title: "Café-Wortschatz", words: [
            { de: "Ich hätte gern …", en: "I'd like …" }, { de: "die Speisekarte", en: "menu" },
            { de: "das Frühstück", en: "breakfast" }, { de: "zahlen, bitte", en: "the bill, please" },
            { de: "zusammen / getrennt", en: "together / separately" }, { de: "Das macht … Euro", en: "That comes to … euros" },
            { de: "lecker", en: "tasty" }, { de: "Guten Appetit!", en: "enjoy your meal!" },
          ] },
          { type: "exercise", slug: "a1-cafe-ordnen" },
          { type: "mistakes", items: [
            { wrong: "Ich will einen Kaffee.", right: "Ich hätte gern einen Kaffee. / Ich möchte einen Kaffee.", why: "'will' sounds like a toddler demanding — hätte gern is the adult version." },
            { wrong: "Ein Kaffee, bitte. — bei der Bestellung von zwei Getränken: Zwei Kaffee", right: "Zwei Kaffee, bitte.", why: "Drinks usually stay singular in orders: zwei Kaffee, drei Bier." },
          ] },
        ],
        homework: { tasks: ["Write your dream breakfast order as a mini dialogue (4 lines).", "Practice: order out loud for you and an imaginary friend — different drinks, ask for the bill."] },
      },
      {
        slug: "a1-mein-tag",
        title: "Mein Tag",
        subtitle: "Daily routine, times and separable verbs preview",
        durationMin: 30,
        objectives: ["Describe your daily routine chronologically", "Tell the time (official and colloquial)", "Use aufstehen and other daily verbs"],
        blocks: [
          { type: "heading", text: "Von morgens bis abends" },
          { type: "dialogue", title: "Ein ganz normaler Tag", lines: [
            { speaker: "Omar", de: "Ich stehe um halb sieben auf und dusche.", en: "I get up at half past six and shower." },
            { speaker: "Omar", de: "Um sieben frühstücke ich — Brot mit Käse und einen Tee.", en: "At seven I have breakfast — bread with cheese and a tea." },
            { speaker: "Omar", de: "Von neun bis fünf arbeite ich. Um sechs koche ich Abendessen.", en: "From nine to five I work. At six I cook dinner." },
            { speaker: "Omar", de: "Abends lerne ich Deutsch und um elf gehe ich ins Bett.", en: "In the evenings I study German and at eleven I go to bed." },
          ] },
          { type: "callout", variant: "warning", title: "halb sieben = 6:30!", md: "German 'halb' looks FORWARD to the next hour: **halb sieben = 6:30** (half of the way to seven), not 7:30. This causes more missed appointments than anything else in the language." },
          { type: "table", title: "Uhrzeit: offiziell & im Alltag", headers: ["Uhr", "offiziell", "umgangssprachlich"], rows: [["6:30", "sechs Uhr dreißig", "halb sieben ⚠️"], ["7:15", "sieben Uhr fünfzehn", "Viertel nach sieben"], ["7:45", "sieben Uhr fünfundvierzig", "Viertel vor acht"], ["19:00", "neunzehn Uhr", "sieben (Uhr abends)"]] },
          { type: "text", md: "Notice **Ich stehe … auf** — the verb *aufstehen* splits, and *auf* jumps to the end. These 'separable verbs' rule daily-routine German: *aufstehen, einkaufen, fernsehen, anrufen*. You'll master them properly in A2 — for now, learn the sentences as chunks." },
          { type: "exercise", slug: "a1-uhrzeit-mcq" },
          { type: "exercise", slug: "a1-praesens-endungen" },
        ],
        homework: { tasks: ["Write your own day in 6 sentences with times (use the dialogue as a template).", "Say tomorrow's plan out loud while getting ready in the morning.", "Bonus: what time is 'halb zehn'? Answer without thinking — then check."] },
      },
    ],
  },
  {
    slug: "a1-unterwegs",
    title: "Unterwegs",
    description: "Shopping, your home — and the final review before your A1 test.",
    icon: "shopping-cart",
    lessons: [
      {
        slug: "a1-einkaufen",
        title: "Einkaufen gehen",
        subtitle: "Im Supermarkt: quantities, prices and Akkusativ in action",
        durationMin: 25,
        objectives: ["Shop for groceries with quantities", "Use the Akkusativ naturally with kaufen/brauchen", "Ask where things are"],
        blocks: [
          { type: "heading", text: "Im Supermarkt" },
          { type: "dialogue", title: "An der Käsetheke", lines: [
            { speaker: "Verkäuferin", de: "Guten Tag, was darf es sein?", en: "Hello, what would you like?" },
            { speaker: "Lena", de: "Ich hätte gern 200 Gramm Gouda, bitte.", en: "I'd like 200 grams of Gouda, please." },
            { speaker: "Verkäuferin", de: "Gern. Sonst noch etwas?", en: "Certainly. Anything else?" },
            { speaker: "Lena", de: "Ja, wo finde ich die Milch?", en: "Yes, where do I find the milk?" },
            { speaker: "Verkäuferin", de: "Gang drei, ganz hinten links.", en: "Aisle three, at the very back on the left." },
          ] },
          { type: "vocab", title: "Mengen & Verpackungen", words: [
            { de: "ein Kilo / ein Pfund", en: "a kilo / 500g" }, { de: "200 Gramm", en: "200 grams" },
            { de: "eine Flasche Wasser", en: "a bottle of water" }, { de: "eine Packung Reis", en: "a pack of rice" },
            { de: "ein Stück Kuchen", en: "a piece of cake" }, { de: "eine Dose Tomaten", en: "a can of tomatoes" },
          ] },
          { type: "callout", variant: "grammar", title: "kaufen + Akkusativ", md: "Shopping is Akkusativ training: *Ich kaufe **einen** Apfel, **eine** Banane, **ein** Brot.* Only der-words change (der → den, ein → einen): *Ich brauche **einen** Regenschirm.*" },
          { type: "exercise", slug: "a1-akkusativ-gap" },
          { type: "callout", variant: "culture", title: "Pfand & Öffnungszeiten", md: "Bottles carry **Pfand** (deposit, 8–25 ct) — return them at the machine. And plan ahead: on **Sundays almost every shop is closed**. Saturday evening panic-shopping is a German tradition." },
        ],
        homework: { tasks: ["Write your real shopping list for the week — in German with quantities.", "Practice the dialogue swapping in three different products."] },
      },
      {
        slug: "a1-meine-wohnung",
        title: "Meine Wohnung",
        subtitle: "Rooms, furniture and describing where you live",
        durationMin: 25,
        objectives: ["Name rooms and furniture with articles", "Describe your home with adjectives", "Understand simple housing ads"],
        blocks: [
          { type: "heading", text: "Zeig mir deine Wohnung!" },
          { type: "text", md: "Germans love talking about ihre Wohnung — rent, size, light, neighbors. Learn to describe yours: *Meine Wohnung hat zwei Zimmer, eine Küche und ein Bad. Sie ist klein, aber hell.*" },
          { type: "table", title: "Wohnungsanzeigen entschlüsseln", headers: ["Abkürzung", "Bedeutung", "auf Englisch"], rows: [["2 ZKB", "2 Zimmer, Küche, Bad", "2 rooms, kitchen, bath"], ["NK", "Nebenkosten", "utility costs"], ["KM / WM", "Kaltmiete / Warmmiete", "rent without/with utilities"], ["EG / 3. OG", "Erdgeschoss / 3. Obergeschoss", "ground / 3rd floor"], ["WG", "Wohngemeinschaft", "shared flat"]] },
          { type: "examples", items: [
            { de: "Das Wohnzimmer ist groß und hell.", en: "The living room is big and bright." },
            { de: "Mein Bett steht im Schlafzimmer.", en: "My bed is in the bedroom." },
            { de: "Die Miete kostet 650 Euro warm.", en: "The rent is 650 euros including utilities." },
          ] },
          { type: "vocab", title: "Möbel-Basics", words: [
            { de: "der Tisch", en: "table" }, { de: "der Stuhl", en: "chair" }, { de: "das Bett", en: "bed" },
            { de: "der Schrank", en: "wardrobe" }, { de: "das Sofa", en: "sofa" }, { de: "die Lampe", en: "lamp" },
            { de: "der Kühlschrank", en: "fridge" }, { de: "die Waschmaschine", en: "washing machine" },
          ] },
          { type: "exercise", slug: "a1-wohnung-match" },
        ],
        homework: { tasks: ["Describe your home in 5 sentences: rooms, size, favorite spot.", "Find one real German housing ad online and decode the abbreviations."] },
      },
      {
        slug: "a1-wiederholung",
        title: "Wiederholung A1",
        subtitle: "Everything so far — condensed and connected",
        type: "REVISION",
        durationMin: 30,
        xpReward: 60,
        objectives: ["Review all A1 structures in context", "Find and fix your personal weak spots"],
        blocks: [
          { type: "heading", text: "Der große Rückblick" },
          { type: "text", md: "You've covered a LOT: greetings, sein & haben, regular verbs, articles, Akkusativ, questions, negation, numbers, time — plus café, shopping and housing vocabulary. This revision connects it all into one story." },
          { type: "text", md: "**Lies den Text:**\n\nOmar ist 26 und kommt aus Marokko. Er wohnt jetzt in Köln und lernt Deutsch. Sein Tag: Er steht um halb sieben auf, frühstückt Brot mit Käse und fährt zur Arbeit. Abends kauft er im Supermarkt ein — er braucht einen Apfel, eine Packung Reis und kein Bier. Seine Wohnung ist klein, aber hell, und die Miete ist nicht teuer. Am Wochenende trifft er Freunde im Café und bestellt immer einen Tee. „Ich hätte gern einen Tee, bitte!\"" },
          { type: "callout", variant: "tip", title: "Selbst-Check", md: "Can you spot in the text: 1× separable verb, 2× Akkusativ objects, 1× negation with kein, 1× time expression? Find them before you do the exercises below." },
          { type: "exercise", slug: "a1-sein-haben-gap" },
          { type: "exercise", slug: "a1-negation-mcq" },
          { type: "exercise", slug: "a1-fragen-ordnen" },
        ],
        homework: { tasks: ["Rewrite the Omar text about yourself — same structures, your life.", "Review ALL your due flashcards today.", "Book the mini test: tomorrow, fresh brain, no notes."] },
      },
      {
        slug: "a1-mini-test",
        title: "Mini-Test A1",
        subtitle: "Prove your A1 skills — no notes, real conditions",
        type: "MINI_TEST",
        durationMin: 20,
        xpReward: 100,
        objectives: ["Test yourself under exam-like conditions"],
        blocks: [
          { type: "heading", text: "Zeig, was du kannst!" },
          { type: "text", md: "Three exercises, **no notes, no dictionary**. Score 80%+ overall and you're solidly on track. Below that? No problem — the results show you exactly which lessons to revisit. Viel Erfolg! 🍀" },
          { type: "exercise", slug: "a1-test-grammatik" },
          { type: "exercise", slug: "a1-artikel-match" },
          { type: "exercise", slug: "a1-test-alltag" },
          { type: "callout", variant: "info", title: "Und jetzt?", md: "**Passed?** On to A2 — the Perfekt and real conversations await. **Want the full experience?** Take the timed **Goethe A1 mock exam** under Mock Exams before you move on." },
        ],
      },
    ],
  },
];
