import type { VocabTopicSeed } from "./types";

/** B1 & B2 vocabulary topic packs */
export const VOCAB_B: VocabTopicSeed[] = [
  {
    slug: "meinung-diskussion",
    levelCode: "B1",
    title: "Meinung & Diskussion",
    description: "Express, defend and soften opinions like a native.",
    icon: "message-circle",
    words: [
      { german: "die Meinung", article: "die", plural: "Meinungen", ipa: "ˈmaɪ̯nʊŋ", meaning: "opinion", exampleDe: "Meiner Meinung nach ist das falsch.", exampleEn: "In my opinion, that's wrong.", expressions: [{ de: "meiner Meinung nach", en: "in my opinion" }], difficulty: 2 },
      { german: "zustimmen", pos: "verb", meaning: "to agree", exampleDe: "Da stimme ich dir völlig zu.", exampleEn: "I completely agree with you there.", opposites: ["widersprechen"], memoryTip: "Separable + Dativ: ich stimme DIR zu.", difficulty: 2 },
      { german: "widersprechen", pos: "verb", meaning: "to contradict, to disagree", exampleDe: "Ich muss Ihnen leider widersprechen.", exampleEn: "I'm afraid I have to disagree with you.", opposites: ["zustimmen"], difficulty: 3 },
      { german: "der Vorteil", article: "der", plural: "Vorteile", meaning: "advantage", exampleDe: "Ein großer Vorteil ist der Preis.", exampleEn: "A big advantage is the price.", opposites: ["der Nachteil"], difficulty: 2 },
      { german: "der Nachteil", article: "der", plural: "Nachteile", meaning: "disadvantage", exampleDe: "Der einzige Nachteil ist die Lage.", exampleEn: "The only disadvantage is the location.", opposites: ["der Vorteil"], difficulty: 2 },
      { german: "der Grund", article: "der", plural: "Gründe", meaning: "reason", exampleDe: "Es gibt viele Gründe dafür.", exampleEn: "There are many reasons for it.", expressions: [{ de: "aus diesem Grund", en: "for this reason" }], difficulty: 2 },
      { german: "das Argument", article: "das", plural: "Argumente", meaning: "argument (point)", exampleDe: "Das ist ein starkes Argument.", exampleEn: "That's a strong argument.", difficulty: 2 },
      { german: "überzeugen", pos: "verb", meaning: "to convince", exampleDe: "Du hast mich überzeugt.", exampleEn: "You've convinced me.", difficulty: 3 },
      { german: "behaupten", pos: "verb", meaning: "to claim", exampleDe: "Er behauptet, dass es stimmt.", exampleEn: "He claims that it's true.", difficulty: 3 },
      { german: "die Diskussion", article: "die", plural: "Diskussionen", meaning: "discussion", exampleDe: "Die Diskussion war sehr lebhaft.", exampleEn: "The discussion was very lively.", synonyms: ["die Debatte"], difficulty: 2 },
      { german: "der Standpunkt", article: "der", plural: "Standpunkte", meaning: "point of view", exampleDe: "Ich verstehe deinen Standpunkt.", exampleEn: "I understand your point of view.", synonyms: ["die Sichtweise"], difficulty: 3 },
      { german: "einerseits … andererseits", pos: "phrase", meaning: "on the one hand … on the other hand", exampleDe: "Einerseits ist es teuer, andererseits sehr praktisch.", exampleEn: "On the one hand it's expensive, on the other very practical.", memoryTip: "The magic B1 exam structure — use it in every discussion!", difficulty: 3 },
      { german: "es kommt darauf an", pos: "phrase", meaning: "it depends", exampleDe: "Es kommt darauf an, wie viel Zeit wir haben.", exampleEn: "It depends on how much time we have.", difficulty: 3 },
      { german: "vorschlagen", pos: "verb", meaning: "to suggest", exampleDe: "Ich schlage vor, dass wir abstimmen.", exampleEn: "I suggest we vote.", difficulty: 2 },
      { german: "die Lösung", article: "die", plural: "Lösungen", meaning: "solution", exampleDe: "Wir müssen eine Lösung finden.", exampleEn: "We have to find a solution.", difficulty: 2 },
      { german: "das Thema", article: "das", plural: "Themen", meaning: "topic", exampleDe: "Das ist ein schwieriges Thema.", exampleEn: "That's a difficult topic.", difficulty: 1 },
      { german: "die Erfahrung", article: "die", plural: "Erfahrungen", meaning: "experience", exampleDe: "Aus eigener Erfahrung weiß ich, dass …", exampleEn: "From my own experience I know that…", difficulty: 2 },
      { german: "wahrscheinlich", pos: "adverb", meaning: "probably", exampleDe: "Wahrscheinlich hast du recht.", exampleEn: "You're probably right.", synonyms: ["vermutlich"], difficulty: 2 },
      { german: "auf jeden Fall", pos: "phrase", meaning: "definitely, in any case", exampleDe: "Das lohnt sich auf jeden Fall.", exampleEn: "It's definitely worth it.", opposites: ["auf keinen Fall"], difficulty: 2 },
      { german: "recht haben", pos: "phrase", meaning: "to be right", exampleDe: "Du hattest recht!", exampleEn: "You were right!", difficulty: 2 },
    ],
  },
  {
    slug: "umwelt-natur",
    levelCode: "B1",
    title: "Umwelt & Natur",
    description: "Environment, climate and sustainability — a favorite exam topic.",
    icon: "leaf",
    words: [
      { german: "die Umwelt", article: "die", ipa: "ˈʊmvɛlt", meaning: "environment", exampleDe: "Wir müssen die Umwelt schützen.", exampleEn: "We have to protect the environment.", difficulty: 2 },
      { german: "der Umweltschutz", article: "der", meaning: "environmental protection", exampleDe: "Umweltschutz ist ein wichtiges Thema.", exampleEn: "Environmental protection is an important topic.", difficulty: 3 },
      { german: "das Klima", article: "das", meaning: "climate", exampleDe: "Das Klima verändert sich.", exampleEn: "The climate is changing.", expressions: [{ de: "der Klimawandel", en: "climate change" }], difficulty: 2 },
      { german: "der Müll", article: "der", meaning: "garbage, waste", exampleDe: "Bitte trennen Sie den Müll.", exampleEn: "Please separate the waste.", synonyms: ["der Abfall"], memoryTip: "Mülltrennung is practically a German national sport.", difficulty: 2 },
      { german: "recyceln", pos: "verb", meaning: "to recycle", exampleDe: "Glas und Papier werden recycelt.", exampleEn: "Glass and paper are recycled.", difficulty: 2 },
      { german: "die Energie", article: "die", plural: "Energien", meaning: "energy", exampleDe: "Erneuerbare Energien werden wichtiger.", exampleEn: "Renewable energies are becoming more important.", difficulty: 2 },
      { german: "der Strom", article: "der", meaning: "electricity; stream", exampleDe: "Der Strom kommt aus Solaranlagen.", exampleEn: "The electricity comes from solar plants.", difficulty: 2 },
      { german: "sparen", pos: "verb", meaning: "to save (money/energy)", exampleDe: "Wir sollten Wasser sparen.", exampleEn: "We should save water.", opposites: ["verschwenden"], difficulty: 2 },
      { german: "verschmutzen", pos: "verb", meaning: "to pollute", exampleDe: "Plastik verschmutzt die Meere.", exampleEn: "Plastic pollutes the oceans.", difficulty: 3 },
      { german: "die Luft", article: "die", meaning: "air", exampleDe: "Die Luft in den Bergen ist sauber.", exampleEn: "The air in the mountains is clean.", difficulty: 1 },
      { german: "der Wald", article: "der", plural: "Wälder", ipa: "valt", meaning: "forest", exampleDe: "Wir machen einen Spaziergang im Wald.", exampleEn: "We're taking a walk in the forest.", difficulty: 1 },
      { german: "das Meer", article: "das", plural: "Meere", meaning: "sea, ocean", exampleDe: "Im Sommer fahren wir ans Meer.", exampleEn: "In summer we go to the sea.", synonyms: ["die See"], difficulty: 1 },
      { german: "schützen", pos: "verb", meaning: "to protect", exampleDe: "Wir müssen die Tiere schützen.", exampleEn: "We have to protect the animals.", difficulty: 2 },
      { german: "vermeiden", pos: "verb", meaning: "to avoid", exampleDe: "Ich versuche, Plastik zu vermeiden.", exampleEn: "I try to avoid plastic.", difficulty: 3 },
      { german: "öffentliche Verkehrsmittel", article: "die", pos: "noun (pl.)", meaning: "public transport", exampleDe: "Ich fahre mit öffentlichen Verkehrsmitteln.", exampleEn: "I use public transport.", difficulty: 3 },
      { german: "das Fahrrad", article: "das", plural: "Fahrräder", meaning: "bicycle", exampleDe: "Mit dem Fahrrad bin ich schneller.", exampleEn: "I'm faster by bike.", synonyms: ["das Rad"], difficulty: 1 },
      { german: "nachhaltig", pos: "adjective", meaning: "sustainable", exampleDe: "Wir wollen nachhaltiger leben.", exampleEn: "We want to live more sustainably.", memoryTip: "THE buzzword of modern German — great for B1/B2 essays.", difficulty: 3 },
      { german: "die Verpackung", article: "die", plural: "Verpackungen", meaning: "packaging", exampleDe: "Zu viel Verpackung ist unnötig.", exampleEn: "Too much packaging is unnecessary.", difficulty: 3 },
      { german: "das Pfand", article: "das", meaning: "deposit (on bottles)", exampleDe: "Auf der Flasche sind 25 Cent Pfand.", exampleEn: "There's a 25-cent deposit on the bottle.", memoryTip: "Return bottles to the machine at the supermarket — real money back!", difficulty: 3 },
      { german: "verursachen", pos: "verb", meaning: "to cause", exampleDe: "Autos verursachen viel CO2.", exampleEn: "Cars cause a lot of CO2.", difficulty: 3 },
    ],
  },
  {
    slug: "medien-technik",
    levelCode: "B1",
    title: "Medien & Technik",
    description: "Phones, internet and digital life.",
    icon: "laptop",
    words: [
      { german: "das Handy", article: "das", plural: "Handys", ipa: "ˈhɛndi", meaning: "mobile phone", exampleDe: "Mein Handy ist kaputt.", exampleEn: "My phone is broken.", memoryTip: "Sounds English, is 100% German — no native speaker says 'mobile phone'.", difficulty: 1 },
      { german: "der Computer", article: "der", plural: "Computer", meaning: "computer", exampleDe: "Ich arbeite den ganzen Tag am Computer.", exampleEn: "I work at the computer all day.", synonyms: ["der Rechner"], difficulty: 1 },
      { german: "das Internet", article: "das", meaning: "internet", exampleDe: "Ohne Internet geht heute nichts mehr.", exampleEn: "Nothing works without the internet these days.", difficulty: 1 },
      { german: "die Nachricht", article: "die", plural: "Nachrichten", meaning: "message; news", exampleDe: "Ich schicke dir eine Nachricht.", exampleEn: "I'll send you a message.", memoryTip: "die Nachrichten (pl.) = the news on TV.", difficulty: 2 },
      { german: "herunterladen", pos: "verb", meaning: "to download", exampleDe: "Ich habe die App heruntergeladen.", exampleEn: "I downloaded the app.", opposites: ["hochladen"], difficulty: 3 },
      { german: "die Datei", article: "die", plural: "Dateien", meaning: "file (computer)", exampleDe: "Die Datei ist zu groß.", exampleEn: "The file is too big.", difficulty: 2 },
      { german: "das Passwort", article: "das", plural: "Passwörter", meaning: "password", exampleDe: "Ich habe mein Passwort vergessen.", exampleEn: "I forgot my password.", difficulty: 2 },
      { german: "die Webseite", article: "die", plural: "Webseiten", meaning: "website", exampleDe: "Die Webseite lädt nicht.", exampleEn: "The website isn't loading.", difficulty: 2 },
      { german: "die Werbung", article: "die", meaning: "advertising", exampleDe: "Überall ist Werbung.", exampleEn: "There's advertising everywhere.", difficulty: 2 },
      { german: "die Sendung", article: "die", plural: "Sendungen", meaning: "TV/radio program; shipment", exampleDe: "Die Sendung läuft um 20:15 Uhr.", exampleEn: "The program is on at 8:15 pm.", difficulty: 2 },
      { german: "die Zeitung", article: "die", plural: "Zeitungen", meaning: "newspaper", exampleDe: "Er liest jeden Morgen Zeitung.", exampleEn: "He reads the newspaper every morning.", difficulty: 1 },
      { german: "drucken", pos: "verb", meaning: "to print", exampleDe: "Kannst du das Dokument drucken?", exampleEn: "Can you print the document?", memoryTip: "drucken (print) vs. drücken (press/push) — the umlaut changes everything!", difficulty: 2 },
      { german: "speichern", pos: "verb", meaning: "to save (a file)", exampleDe: "Vergiss nicht zu speichern!", exampleEn: "Don't forget to save!", difficulty: 2 },
      { german: "löschen", pos: "verb", meaning: "to delete", exampleDe: "Ich habe das Foto gelöscht.", exampleEn: "I deleted the photo.", difficulty: 2 },
      { german: "funktionieren", pos: "verb", meaning: "to work, to function", exampleDe: "Der Drucker funktioniert nicht.", exampleEn: "The printer isn't working.", synonyms: ["gehen"], difficulty: 2 },
      { german: "kaputt", pos: "adjective", meaning: "broken", exampleDe: "Das Ladekabel ist kaputt.", exampleEn: "The charging cable is broken.", difficulty: 1 },
      { german: "der Bildschirm", article: "der", plural: "Bildschirme", meaning: "screen", exampleDe: "Der Bildschirm ist zu dunkel.", exampleEn: "The screen is too dark.", difficulty: 2 },
      { german: "sozial", pos: "adjective", meaning: "social", exampleDe: "Soziale Medien sind ein großes Thema.", exampleEn: "Social media is a big topic.", expressions: [{ de: "die sozialen Medien", en: "social media" }], difficulty: 2 },
      { german: "abhängig", pos: "adjective", meaning: "dependent, addicted", exampleDe: "Viele sind vom Handy abhängig.", exampleEn: "Many people are addicted to their phones.", difficulty: 3 },
      { german: "der Vorteil", article: "der", plural: "Vorteile", meaning: "advantage", exampleDe: "Das Internet hat viele Vorteile.", exampleEn: "The internet has many advantages.", difficulty: 2 },
    ],
  },
  {
    slug: "beruf-karriere-b2",
    levelCode: "B2",
    title: "Beruf & Karriere",
    description: "Professional German for applications, meetings and career growth.",
    icon: "briefcase",
    words: [
      { german: "die Herausforderung", article: "die", plural: "Herausforderungen", meaning: "challenge", exampleDe: "Ich suche eine neue Herausforderung.", exampleEn: "I'm looking for a new challenge.", memoryTip: "The word every German job interview requires at least twice.", difficulty: 3 },
      { german: "die Verantwortung", article: "die", meaning: "responsibility", exampleDe: "Ich übernehme gern Verantwortung.", exampleEn: "I like taking on responsibility.", expressions: [{ de: "Verantwortung übernehmen", en: "to take responsibility" }], difficulty: 3 },
      { german: "die Fähigkeit", article: "die", plural: "Fähigkeiten", meaning: "ability, skill", exampleDe: "Kommunikative Fähigkeiten sind wichtig.", exampleEn: "Communication skills are important.", synonyms: ["die Kompetenz"], difficulty: 3 },
      { german: "die Voraussetzung", article: "die", plural: "Voraussetzungen", meaning: "prerequisite, requirement", exampleDe: "Gute Deutschkenntnisse sind Voraussetzung.", exampleEn: "Good German skills are a requirement.", difficulty: 3 },
      { german: "sich bewerben um", pos: "verb", meaning: "to apply for", exampleDe: "Ich bewerbe mich um die Stelle als Pflegekraft.", exampleEn: "I'm applying for the position as a caregiver.", difficulty: 3 },
      { german: "das Vorstellungsgespräch", article: "das", plural: "Vorstellungsgespräche", meaning: "job interview", exampleDe: "Morgen habe ich ein Vorstellungsgespräch.", exampleEn: "I have a job interview tomorrow.", difficulty: 3 },
      { german: "die Weiterbildung", article: "die", plural: "Weiterbildungen", meaning: "further training", exampleDe: "Die Firma bietet Weiterbildungen an.", exampleEn: "The company offers further training.", difficulty: 3 },
      { german: "die Führungskraft", article: "die", plural: "Führungskräfte", meaning: "manager, executive", exampleDe: "Sie ist eine erfahrene Führungskraft.", exampleEn: "She is an experienced executive.", difficulty: 3 },
      { german: "der Mitarbeiter", article: "der", plural: "Mitarbeiter", meaning: "employee (m)", exampleDe: "Alle Mitarbeiter bekommen einen Bonus.", exampleEn: "All employees get a bonus.", synonyms: ["der Angestellte"], difficulty: 2 },
      { german: "die Abteilung", article: "die", plural: "Abteilungen", meaning: "department", exampleDe: "Er leitet die Abteilung Marketing.", exampleEn: "He heads the marketing department.", difficulty: 3 },
      { german: "das Ziel", article: "das", plural: "Ziele", meaning: "goal", exampleDe: "Wir haben unsere Ziele erreicht.", exampleEn: "We reached our goals.", expressions: [{ de: "ein Ziel erreichen", en: "to reach a goal" }], difficulty: 2 },
      { german: "verhandeln", pos: "verb", meaning: "to negotiate", exampleDe: "Über das Gehalt kann man verhandeln.", exampleEn: "The salary is negotiable.", difficulty: 3 },
      { german: "die Frist", article: "die", plural: "Fristen", meaning: "deadline", exampleDe: "Die Frist läuft am Freitag ab.", exampleEn: "The deadline expires on Friday.", synonyms: ["der Termin"], difficulty: 3 },
      { german: "zuverlässig", pos: "adjective", meaning: "reliable", exampleDe: "Sie arbeitet sehr zuverlässig.", exampleEn: "She works very reliably.", memoryTip: "Top-3 word in German job ads and references.", difficulty: 3 },
      { german: "selbstständig", pos: "adjective", meaning: "independent; self-employed", exampleDe: "Ich arbeite gern selbstständig.", exampleEn: "I like working independently.", difficulty: 3 },
      { german: "belastbar", pos: "adjective", meaning: "resilient, able to work under pressure", exampleDe: "Für den Job muss man belastbar sein.", exampleEn: "You need to handle pressure for this job.", difficulty: 3 },
      { german: "der Werdegang", article: "der", meaning: "career path", exampleDe: "Erzählen Sie uns von Ihrem Werdegang.", exampleEn: "Tell us about your career path.", difficulty: 3 },
      { german: "einstellen", pos: "verb", meaning: "to hire; to adjust", exampleDe: "Die Firma stellt neue Leute ein.", exampleEn: "The company is hiring new people.", opposites: ["entlassen"], difficulty: 3 },
      { german: "entlassen", pos: "verb", meaning: "to lay off, to dismiss", exampleDe: "Zwanzig Mitarbeiter wurden entlassen.", exampleEn: "Twenty employees were laid off.", opposites: ["einstellen"], difficulty: 3 },
      { german: "die Gehaltsvorstellung", article: "die", plural: "Gehaltsvorstellungen", meaning: "salary expectation", exampleDe: "Nennen Sie bitte Ihre Gehaltsvorstellung.", exampleEn: "Please state your salary expectation.", difficulty: 3 },
    ],
  },
  {
    slug: "gesellschaft-politik",
    levelCode: "B2",
    title: "Gesellschaft & Politik",
    description: "Society, rights and public life — for debates and essays.",
    icon: "landmark",
    words: [
      { german: "die Gesellschaft", article: "die", plural: "Gesellschaften", meaning: "society", exampleDe: "Unsere Gesellschaft verändert sich schnell.", exampleEn: "Our society is changing quickly.", difficulty: 3 },
      { german: "die Regierung", article: "die", plural: "Regierungen", meaning: "government", exampleDe: "Die Regierung plant neue Gesetze.", exampleEn: "The government is planning new laws.", difficulty: 3 },
      { german: "das Gesetz", article: "das", plural: "Gesetze", meaning: "law", exampleDe: "Das neue Gesetz gilt ab Januar.", exampleEn: "The new law applies from January.", difficulty: 3 },
      { german: "das Recht", article: "das", plural: "Rechte", meaning: "right; law", exampleDe: "Jeder hat das Recht auf Bildung.", exampleEn: "Everyone has the right to education.", expressions: [{ de: "das Recht auf", en: "the right to" }], difficulty: 3 },
      { german: "die Wahl", article: "die", plural: "Wahlen", meaning: "election; choice", exampleDe: "Die Wahl findet im September statt.", exampleEn: "The election takes place in September.", expressions: [{ de: "zur Wahl gehen", en: "to go to vote" }], difficulty: 3 },
      { german: "wählen", pos: "verb", meaning: "to vote; to choose", exampleDe: "Ab 18 darf man wählen.", exampleEn: "From 18 you're allowed to vote.", difficulty: 2 },
      { german: "die Freiheit", article: "die", plural: "Freiheiten", meaning: "freedom", exampleDe: "Meinungsfreiheit ist ein Grundrecht.", exampleEn: "Freedom of speech is a basic right.", difficulty: 3 },
      { german: "die Gerechtigkeit", article: "die", meaning: "justice, fairness", exampleDe: "Sie kämpft für soziale Gerechtigkeit.", exampleEn: "She fights for social justice.", difficulty: 3 },
      { german: "die Bevölkerung", article: "die", meaning: "population", exampleDe: "Die Bevölkerung wird älter.", exampleEn: "The population is getting older.", difficulty: 3 },
      { german: "der Bürger", article: "der", plural: "Bürger", meaning: "citizen (m)", exampleDe: "Die Bürger sind unzufrieden.", exampleEn: "The citizens are dissatisfied.", difficulty: 3 },
      { german: "die Integration", article: "die", meaning: "integration", exampleDe: "Sprache ist der Schlüssel zur Integration.", exampleEn: "Language is the key to integration.", difficulty: 3 },
      { german: "die Migration", article: "die", meaning: "migration", exampleDe: "Migration ist ein globales Phänomen.", exampleEn: "Migration is a global phenomenon.", difficulty: 3 },
      { german: "die Bildung", article: "die", meaning: "education", exampleDe: "Bildung sollte kostenlos sein.", exampleEn: "Education should be free.", difficulty: 2 },
      { german: "die Steuer", article: "die", plural: "Steuern", meaning: "tax", exampleDe: "In Deutschland zahlt man hohe Steuern.", exampleEn: "In Germany you pay high taxes.", difficulty: 3 },
      { german: "die Armut", article: "die", meaning: "poverty", exampleDe: "Armut ist auch in reichen Ländern ein Problem.", exampleEn: "Poverty is a problem even in rich countries.", opposites: ["der Reichtum"], difficulty: 3 },
      { german: "die Entwicklung", article: "die", plural: "Entwicklungen", meaning: "development", exampleDe: "Das ist eine positive Entwicklung.", exampleEn: "That's a positive development.", difficulty: 3 },
      { german: "sich engagieren", pos: "verb", meaning: "to get involved, to volunteer", exampleDe: "Sie engagiert sich für Geflüchtete.", exampleEn: "She volunteers for refugees.", difficulty: 3 },
      { german: "die Verantwortung", article: "die", meaning: "responsibility", exampleDe: "Die Politik trägt Verantwortung dafür.", exampleEn: "Politics bears responsibility for it.", difficulty: 3 },
      { german: "öffentlich", pos: "adjective", meaning: "public", exampleDe: "Das ist eine öffentliche Debatte.", exampleEn: "That's a public debate.", opposites: ["privat"], difficulty: 2 },
      { german: "die Maßnahme", article: "die", plural: "Maßnahmen", meaning: "measure, action", exampleDe: "Die Regierung ergreift neue Maßnahmen.", exampleEn: "The government is taking new measures.", expressions: [{ de: "Maßnahmen ergreifen", en: "to take measures" }], difficulty: 3 },
    ],
  },
];
