import type { VocabTopicSeed } from "./types";

/** A1 & A2 vocabulary topic packs */
export const VOCAB_A: VocabTopicSeed[] = [
  {
    slug: "begruessung-basics",
    levelCode: "A1",
    title: "Begrüßung & Basics",
    description: "Your very first words — greetings, courtesy and survival phrases.",
    icon: "hand",
    words: [
      { german: "Hallo", pos: "interjection", ipa: "haˈloː", meaning: "hello", exampleDe: "Hallo, wie geht's?", exampleEn: "Hello, how are you?", synonyms: ["Guten Tag", "Servus"], difficulty: 1 },
      { german: "Guten Morgen", pos: "phrase", meaning: "good morning", exampleDe: "Guten Morgen, Frau Schmidt!", exampleEn: "Good morning, Ms. Schmidt!", difficulty: 1 },
      { german: "Guten Abend", pos: "phrase", meaning: "good evening", exampleDe: "Guten Abend, herzlich willkommen!", exampleEn: "Good evening, welcome!", difficulty: 1 },
      { german: "Tschüss", pos: "interjection", ipa: "tʃʏs", meaning: "bye (informal)", exampleDe: "Tschüss, bis morgen!", exampleEn: "Bye, see you tomorrow!", synonyms: ["Auf Wiedersehen", "Ciao"], difficulty: 1 },
      { german: "Auf Wiedersehen", pos: "phrase", meaning: "goodbye (formal)", exampleDe: "Auf Wiedersehen und vielen Dank!", exampleEn: "Goodbye and thank you very much!", difficulty: 1 },
      { german: "danke", pos: "particle", ipa: "ˈdaŋkə", meaning: "thank you", exampleDe: "Danke für deine Hilfe!", exampleEn: "Thanks for your help!", expressions: [{ de: "Danke schön!", en: "Thank you very much!" }], difficulty: 1 },
      { german: "bitte", pos: "particle", ipa: "ˈbɪtə", meaning: "please / you're welcome", exampleDe: "Einen Kaffee, bitte.", exampleEn: "A coffee, please.", memoryTip: "One little word, three jobs: please, here you go, you're welcome.", difficulty: 1 },
      { german: "ja", pos: "particle", ipa: "jaː", meaning: "yes", exampleDe: "Ja, gern!", exampleEn: "Yes, gladly!", opposites: ["nein"], difficulty: 1 },
      { german: "nein", pos: "particle", ipa: "naɪ̯n", meaning: "no", exampleDe: "Nein, danke.", exampleEn: "No, thank you.", opposites: ["ja"], difficulty: 1 },
      { german: "Entschuldigung", article: "die", plural: "Entschuldigungen", ipa: "ɛntˈʃʊldɪɡʊŋ", meaning: "excuse me; apology", exampleDe: "Entschuldigung, wo ist der Bahnhof?", exampleEn: "Excuse me, where is the train station?", difficulty: 1 },
      { german: "der Name", article: "der", plural: "Namen", ipa: "ˈnaːmə", meaning: "name", exampleDe: "Mein Name ist Anna.", exampleEn: "My name is Anna.", expressions: [{ de: "Wie ist Ihr Name?", en: "What is your name? (formal)" }], difficulty: 1 },
      { german: "die Frage", article: "die", plural: "Fragen", ipa: "ˈfʁaːɡə", meaning: "question", exampleDe: "Ich habe eine Frage.", exampleEn: "I have a question.", opposites: ["die Antwort"], difficulty: 1 },
      { german: "die Antwort", article: "die", plural: "Antworten", meaning: "answer", exampleDe: "Die Antwort ist richtig.", exampleEn: "The answer is correct.", opposites: ["die Frage"], difficulty: 1 },
      { german: "das Land", article: "das", plural: "Länder", ipa: "lant", meaning: "country", exampleDe: "Aus welchem Land kommst du?", exampleEn: "Which country do you come from?", difficulty: 1 },
      { german: "die Sprache", article: "die", plural: "Sprachen", ipa: "ˈʃpʁaːxə", meaning: "language", exampleDe: "Deutsch ist eine schöne Sprache.", exampleEn: "German is a beautiful language.", difficulty: 1 },
      { german: "verstehen", pos: "verb", meaning: "to understand", exampleDe: "Ich verstehe das nicht.", exampleEn: "I don't understand that.", expressions: [{ de: "Verstehst du?", en: "Do you understand?" }], difficulty: 1 },
      { german: "wiederholen", pos: "verb", meaning: "to repeat", exampleDe: "Können Sie das bitte wiederholen?", exampleEn: "Can you repeat that, please?", memoryTip: "wieder (again) + holen (fetch) = fetch it again!", difficulty: 2 },
      { german: "langsam", pos: "adjective", ipa: "ˈlaŋzaːm", meaning: "slow(ly)", exampleDe: "Sprechen Sie bitte langsam.", exampleEn: "Please speak slowly.", opposites: ["schnell"], difficulty: 1 },
      { german: "richtig", pos: "adjective", meaning: "correct, right", exampleDe: "Das ist richtig!", exampleEn: "That's correct!", opposites: ["falsch"], difficulty: 1 },
      { german: "falsch", pos: "adjective", ipa: "falʃ", meaning: "wrong", exampleDe: "Die Nummer ist falsch.", exampleEn: "The number is wrong.", opposites: ["richtig"], difficulty: 1 },
    ],
  },
  {
    slug: "familie-menschen",
    levelCode: "A1",
    title: "Familie & Menschen",
    description: "Family members and the people around you.",
    icon: "users",
    words: [
      { german: "die Familie", article: "die", plural: "Familien", ipa: "faˈmiːli̯ə", meaning: "family", exampleDe: "Meine Familie wohnt in Marokko.", exampleEn: "My family lives in Morocco.", difficulty: 1 },
      { german: "die Mutter", article: "die", plural: "Mütter", ipa: "ˈmʊtɐ", meaning: "mother", exampleDe: "Meine Mutter kocht sehr gut.", exampleEn: "My mother cooks very well.", synonyms: ["die Mama"], difficulty: 1 },
      { german: "der Vater", article: "der", plural: "Väter", ipa: "ˈfaːtɐ", meaning: "father", exampleDe: "Mein Vater arbeitet viel.", exampleEn: "My father works a lot.", synonyms: ["der Papa"], difficulty: 1 },
      { german: "die Eltern", article: "die", pos: "noun (pl.)", meaning: "parents", exampleDe: "Meine Eltern sind sehr nett.", exampleEn: "My parents are very nice.", memoryTip: "Only plural — Germans have no singular 'parent' in everyday speech.", difficulty: 1 },
      { german: "der Bruder", article: "der", plural: "Brüder", ipa: "ˈbʁuːdɐ", meaning: "brother", exampleDe: "Ich habe zwei Brüder.", exampleEn: "I have two brothers.", difficulty: 1 },
      { german: "die Schwester", article: "die", plural: "Schwestern", ipa: "ˈʃvɛstɐ", meaning: "sister", exampleDe: "Meine Schwester ist Ärztin.", exampleEn: "My sister is a doctor.", difficulty: 1 },
      { german: "die Geschwister", article: "die", pos: "noun (pl.)", meaning: "siblings", exampleDe: "Hast du Geschwister?", exampleEn: "Do you have siblings?", difficulty: 2 },
      { german: "das Kind", article: "das", plural: "Kinder", ipa: "kɪnt", meaning: "child", exampleDe: "Das Kind spielt im Garten.", exampleEn: "The child is playing in the garden.", difficulty: 1 },
      { german: "der Sohn", article: "der", plural: "Söhne", meaning: "son", exampleDe: "Ihr Sohn ist fünf Jahre alt.", exampleEn: "Her son is five years old.", opposites: ["die Tochter"], difficulty: 1 },
      { german: "die Tochter", article: "die", plural: "Töchter", meaning: "daughter", exampleDe: "Unsere Tochter lernt Deutsch.", exampleEn: "Our daughter is learning German.", opposites: ["der Sohn"], difficulty: 1 },
      { german: "die Großmutter", article: "die", plural: "Großmütter", meaning: "grandmother", exampleDe: "Meine Großmutter erzählt gern Geschichten.", exampleEn: "My grandmother likes telling stories.", synonyms: ["die Oma"], difficulty: 1 },
      { german: "der Großvater", article: "der", plural: "Großväter", meaning: "grandfather", exampleDe: "Mein Großvater ist 80.", exampleEn: "My grandfather is 80.", synonyms: ["der Opa"], difficulty: 1 },
      { german: "der Mann", article: "der", plural: "Männer", ipa: "man", meaning: "man; husband", exampleDe: "Ihr Mann heißt Peter.", exampleEn: "Her husband is called Peter.", difficulty: 1 },
      { german: "die Frau", article: "die", plural: "Frauen", ipa: "fʁaʊ̯", meaning: "woman; wife; Mrs.", exampleDe: "Die Frau dort ist meine Lehrerin.", exampleEn: "The woman there is my teacher.", difficulty: 1 },
      { german: "der Freund", article: "der", plural: "Freunde", ipa: "fʁɔʏ̯nt", meaning: "friend (m); boyfriend", exampleDe: "Mein Freund kommt aus Spanien.", exampleEn: "My friend comes from Spain.", memoryTip: "'Mein Freund' can mean boyfriend — 'ein Freund von mir' is just a friend!", difficulty: 2 },
      { german: "die Freundin", article: "die", plural: "Freundinnen", meaning: "friend (f); girlfriend", exampleDe: "Ich treffe heute eine Freundin.", exampleEn: "I'm meeting a friend today.", difficulty: 2 },
      { german: "verheiratet", pos: "adjective", meaning: "married", exampleDe: "Sind Sie verheiratet?", exampleEn: "Are you married?", opposites: ["ledig"], difficulty: 2 },
      { german: "ledig", pos: "adjective", meaning: "single (unmarried)", exampleDe: "Ich bin ledig.", exampleEn: "I'm single.", opposites: ["verheiratet"], difficulty: 2 },
      { german: "alt", pos: "adjective", ipa: "alt", meaning: "old", exampleDe: "Wie alt bist du?", exampleEn: "How old are you?", opposites: ["jung"], difficulty: 1 },
      { german: "jung", pos: "adjective", ipa: "jʊŋ", meaning: "young", exampleDe: "Sie ist noch sehr jung.", exampleEn: "She is still very young.", opposites: ["alt"], difficulty: 1 },
    ],
  },
  {
    slug: "essen-trinken",
    levelCode: "A1",
    title: "Essen & Trinken",
    description: "Food, drinks and everything for the café and restaurant.",
    icon: "utensils",
    words: [
      { german: "das Essen", article: "das", meaning: "food; meal", exampleDe: "Das Essen schmeckt sehr gut.", exampleEn: "The food tastes very good.", difficulty: 1 },
      { german: "das Brot", article: "das", plural: "Brote", ipa: "bʁoːt", meaning: "bread", exampleDe: "Ich kaufe frisches Brot beim Bäcker.", exampleEn: "I buy fresh bread at the bakery.", memoryTip: "Germany has over 3,000 kinds of bread — this word matters!", difficulty: 1 },
      { german: "das Brötchen", article: "das", plural: "Brötchen", meaning: "bread roll", exampleDe: "Zwei Brötchen, bitte.", exampleEn: "Two rolls, please.", difficulty: 1 },
      { german: "der Käse", article: "der", ipa: "ˈkɛːzə", meaning: "cheese", exampleDe: "Ich esse gern Käse zum Frühstück.", exampleEn: "I like eating cheese for breakfast.", difficulty: 1 },
      { german: "die Milch", article: "die", ipa: "mɪlç", meaning: "milk", exampleDe: "Kaffee mit Milch, bitte.", exampleEn: "Coffee with milk, please.", difficulty: 1 },
      { german: "das Wasser", article: "das", ipa: "ˈvasɐ", meaning: "water", exampleDe: "Ein stilles Wasser, bitte.", exampleEn: "A still water, please.", memoryTip: "In Germany, ask for 'stilles Wasser' — default is sparkling!", difficulty: 1 },
      { german: "der Kaffee", article: "der", plural: "Kaffees", ipa: "ˈkafe", meaning: "coffee", exampleDe: "Möchtest du einen Kaffee?", exampleEn: "Would you like a coffee?", difficulty: 1 },
      { german: "der Tee", article: "der", plural: "Tees", meaning: "tea", exampleDe: "Ich trinke abends Tee.", exampleEn: "I drink tea in the evening.", difficulty: 1 },
      { german: "der Apfel", article: "der", plural: "Äpfel", ipa: "ˈapfl̩", meaning: "apple", exampleDe: "Der Apfel ist süß.", exampleEn: "The apple is sweet.", difficulty: 1 },
      { german: "das Obst", article: "das", ipa: "oːpst", meaning: "fruit", exampleDe: "Ich esse jeden Tag Obst.", exampleEn: "I eat fruit every day.", opposites: ["das Gemüse"], difficulty: 1 },
      { german: "das Gemüse", article: "das", ipa: "ɡəˈmyːzə", meaning: "vegetables", exampleDe: "Gemüse ist gesund.", exampleEn: "Vegetables are healthy.", difficulty: 1 },
      { german: "das Fleisch", article: "das", ipa: "flaɪ̯ʃ", meaning: "meat", exampleDe: "Ich esse kein Fleisch.", exampleEn: "I don't eat meat.", difficulty: 1 },
      { german: "der Fisch", article: "der", plural: "Fische", meaning: "fish", exampleDe: "Freitags gibt es Fisch.", exampleEn: "On Fridays there's fish.", difficulty: 1 },
      { german: "der Reis", article: "der", meaning: "rice", exampleDe: "Reis mit Gemüse, bitte.", exampleEn: "Rice with vegetables, please.", difficulty: 1 },
      { german: "das Frühstück", article: "das", meaning: "breakfast", exampleDe: "Was isst du zum Frühstück?", exampleEn: "What do you eat for breakfast?", memoryTip: "früh (early) + Stück (piece) — the early piece of the day.", difficulty: 1 },
      { german: "das Mittagessen", article: "das", meaning: "lunch", exampleDe: "Um 12 Uhr gibt es Mittagessen.", exampleEn: "Lunch is at 12 o'clock.", difficulty: 1 },
      { german: "das Abendessen", article: "das", meaning: "dinner", exampleDe: "Zum Abendessen essen wir Brot.", exampleEn: "For dinner we eat bread.", synonyms: ["das Abendbrot"], difficulty: 1 },
      { german: "die Rechnung", article: "die", plural: "Rechnungen", meaning: "bill, check", exampleDe: "Die Rechnung, bitte!", exampleEn: "The bill, please!", difficulty: 2 },
      { german: "lecker", pos: "adjective", ipa: "ˈlɛkɐ", meaning: "tasty, delicious", exampleDe: "Der Kuchen ist total lecker!", exampleEn: "The cake is really delicious!", synonyms: ["köstlich"], difficulty: 1 },
      { german: "schmecken", pos: "verb", meaning: "to taste (good)", exampleDe: "Schmeckt es dir?", exampleEn: "Does it taste good to you?", expressions: [{ de: "Guten Appetit!", en: "Enjoy your meal!" }], difficulty: 2 },
      { german: "bestellen", pos: "verb", meaning: "to order", exampleDe: "Ich möchte bestellen, bitte.", exampleEn: "I'd like to order, please.", difficulty: 2 },
      { german: "der Durst", article: "der", meaning: "thirst", exampleDe: "Ich habe Durst.", exampleEn: "I'm thirsty.", memoryTip: "Germans HAVE thirst (Durst haben), they aren't thirsty.", difficulty: 1 },
      { german: "der Hunger", article: "der", meaning: "hunger", exampleDe: "Hast du Hunger?", exampleEn: "Are you hungry?", difficulty: 1 },
    ],
  },
  {
    slug: "alltag-zeit",
    levelCode: "A1",
    title: "Alltag & Zeit",
    description: "Days, times and your daily routine.",
    icon: "clock",
    words: [
      { german: "die Zeit", article: "die", plural: "Zeiten", ipa: "tsaɪ̯t", meaning: "time", exampleDe: "Ich habe heute keine Zeit.", exampleEn: "I don't have time today.", difficulty: 1 },
      { german: "die Uhr", article: "die", plural: "Uhren", ipa: "uːɐ̯", meaning: "clock; o'clock", exampleDe: "Es ist acht Uhr.", exampleEn: "It's eight o'clock.", difficulty: 1 },
      { german: "der Tag", article: "der", plural: "Tage", ipa: "taːk", meaning: "day", exampleDe: "Heute ist ein schöner Tag.", exampleEn: "Today is a beautiful day.", opposites: ["die Nacht"], difficulty: 1 },
      { german: "die Woche", article: "die", plural: "Wochen", ipa: "ˈvɔxə", meaning: "week", exampleDe: "Nächste Woche habe ich Urlaub.", exampleEn: "Next week I'm on vacation.", difficulty: 1 },
      { german: "das Wochenende", article: "das", plural: "Wochenenden", meaning: "weekend", exampleDe: "Am Wochenende schlafe ich lange.", exampleEn: "On the weekend I sleep in.", difficulty: 1 },
      { german: "der Monat", article: "der", plural: "Monate", meaning: "month", exampleDe: "Der Kurs dauert drei Monate.", exampleEn: "The course lasts three months.", difficulty: 1 },
      { german: "das Jahr", article: "das", plural: "Jahre", ipa: "jaːɐ̯", meaning: "year", exampleDe: "Ich lerne seit einem Jahr Deutsch.", exampleEn: "I've been learning German for a year.", difficulty: 1 },
      { german: "heute", pos: "adverb", ipa: "ˈhɔʏ̯tə", meaning: "today", exampleDe: "Heute arbeite ich nicht.", exampleEn: "I'm not working today.", difficulty: 1 },
      { german: "morgen", pos: "adverb", ipa: "ˈmɔʁɡn̩", meaning: "tomorrow", exampleDe: "Bis morgen!", exampleEn: "See you tomorrow!", memoryTip: "morgen = tomorrow, der Morgen = the morning. 'Morgen früh' = tomorrow morning.", difficulty: 1 },
      { german: "gestern", pos: "adverb", meaning: "yesterday", exampleDe: "Gestern war ich im Kino.", exampleEn: "Yesterday I was at the cinema.", difficulty: 1 },
      { german: "jetzt", pos: "adverb", ipa: "jɛtst", meaning: "now", exampleDe: "Ich muss jetzt gehen.", exampleEn: "I have to go now.", synonyms: ["nun"], difficulty: 1 },
      { german: "immer", pos: "adverb", meaning: "always", exampleDe: "Er kommt immer zu spät.", exampleEn: "He always comes late.", opposites: ["nie"], difficulty: 1 },
      { german: "nie", pos: "adverb", meaning: "never", exampleDe: "Ich trinke nie Alkohol.", exampleEn: "I never drink alcohol.", opposites: ["immer"], difficulty: 1 },
      { german: "oft", pos: "adverb", meaning: "often", exampleDe: "Wir kochen oft zusammen.", exampleEn: "We often cook together.", synonyms: ["häufig"], opposites: ["selten"], difficulty: 1 },
      { german: "früh", pos: "adjective", ipa: "fʁyː", meaning: "early", exampleDe: "Ich stehe früh auf.", exampleEn: "I get up early.", opposites: ["spät"], difficulty: 1 },
      { german: "spät", pos: "adjective", ipa: "ʃpɛːt", meaning: "late", exampleDe: "Es ist schon spät.", exampleEn: "It's already late.", expressions: [{ de: "Wie spät ist es?", en: "What time is it?" }], difficulty: 1 },
      { german: "der Termin", article: "der", plural: "Termine", meaning: "appointment", exampleDe: "Ich habe um drei einen Termin.", exampleEn: "I have an appointment at three.", memoryTip: "THE German word — life in Germany runs on Termine.", difficulty: 2 },
      { german: "der Kalender", article: "der", plural: "Kalender", meaning: "calendar", exampleDe: "Der Termin steht im Kalender.", exampleEn: "The appointment is in the calendar.", difficulty: 2 },
      { german: "die Pause", article: "die", plural: "Pausen", meaning: "break", exampleDe: "Wir machen zehn Minuten Pause.", exampleEn: "We're taking a ten-minute break.", difficulty: 1 },
      { german: "der Feierabend", article: "der", meaning: "end of the workday", exampleDe: "Um fünf Uhr mache ich Feierabend.", exampleEn: "I finish work at five.", memoryTip: "Literally 'celebration evening' — the sacred German after-work time.", difficulty: 2 },
    ],
  },
  {
    slug: "wohnen-zuhause",
    levelCode: "A1",
    title: "Wohnen & Zuhause",
    description: "Your apartment, furniture and rooms.",
    icon: "home",
    words: [
      { german: "die Wohnung", article: "die", plural: "Wohnungen", ipa: "ˈvoːnʊŋ", meaning: "apartment", exampleDe: "Die Wohnung hat drei Zimmer.", exampleEn: "The apartment has three rooms.", difficulty: 1 },
      { german: "das Haus", article: "das", plural: "Häuser", ipa: "haʊ̯s", meaning: "house", exampleDe: "Das Haus ist alt, aber schön.", exampleEn: "The house is old but beautiful.", expressions: [{ de: "zu Hause", en: "at home" }, { de: "nach Hause", en: "(to) home" }], difficulty: 1 },
      { german: "das Zimmer", article: "das", plural: "Zimmer", ipa: "ˈtsɪmɐ", meaning: "room", exampleDe: "Mein Zimmer ist klein.", exampleEn: "My room is small.", difficulty: 1 },
      { german: "die Küche", article: "die", plural: "Küchen", ipa: "ˈkʏçə", meaning: "kitchen", exampleDe: "Wir essen in der Küche.", exampleEn: "We eat in the kitchen.", memoryTip: "Küche (kitchen) vs. Kuchen (cake) — the umlaut is the difference!", difficulty: 1 },
      { german: "das Badezimmer", article: "das", plural: "Badezimmer", meaning: "bathroom", exampleDe: "Das Badezimmer ist links.", exampleEn: "The bathroom is on the left.", synonyms: ["das Bad"], difficulty: 1 },
      { german: "das Schlafzimmer", article: "das", plural: "Schlafzimmer", meaning: "bedroom", exampleDe: "Das Schlafzimmer ist ruhig.", exampleEn: "The bedroom is quiet.", difficulty: 1 },
      { german: "der Tisch", article: "der", plural: "Tische", ipa: "tɪʃ", meaning: "table", exampleDe: "Das Buch liegt auf dem Tisch.", exampleEn: "The book is on the table.", difficulty: 1 },
      { german: "der Stuhl", article: "der", plural: "Stühle", ipa: "ʃtuːl", meaning: "chair", exampleDe: "Nimm dir einen Stuhl!", exampleEn: "Take a chair!", difficulty: 1 },
      { german: "das Bett", article: "das", plural: "Betten", ipa: "bɛt", meaning: "bed", exampleDe: "Ich gehe ins Bett.", exampleEn: "I'm going to bed.", difficulty: 1 },
      { german: "der Schrank", article: "der", plural: "Schränke", meaning: "wardrobe, cupboard", exampleDe: "Die Teller sind im Schrank.", exampleEn: "The plates are in the cupboard.", difficulty: 2 },
      { german: "das Fenster", article: "das", plural: "Fenster", ipa: "ˈfɛnstɐ", meaning: "window", exampleDe: "Mach bitte das Fenster auf!", exampleEn: "Please open the window!", memoryTip: "Germans love 'lüften' — airing rooms through open windows, even in winter.", difficulty: 1 },
      { german: "die Tür", article: "die", plural: "Türen", ipa: "tyːɐ̯", meaning: "door", exampleDe: "Die Tür ist offen.", exampleEn: "The door is open.", difficulty: 1 },
      { german: "der Schlüssel", article: "der", plural: "Schlüssel", ipa: "ˈʃlʏsl̩", meaning: "key", exampleDe: "Wo ist mein Schlüssel?", exampleEn: "Where is my key?", difficulty: 1 },
      { german: "die Miete", article: "die", plural: "Mieten", meaning: "rent", exampleDe: "Die Miete ist zu hoch.", exampleEn: "The rent is too high.", difficulty: 2 },
      { german: "groß", pos: "adjective", ipa: "ɡʁoːs", meaning: "big, tall", exampleDe: "Die Küche ist groß und hell.", exampleEn: "The kitchen is big and bright.", opposites: ["klein"], difficulty: 1 },
      { german: "klein", pos: "adjective", ipa: "klaɪ̯n", meaning: "small", exampleDe: "Wir haben ein kleines Bad.", exampleEn: "We have a small bathroom.", opposites: ["groß"], difficulty: 1 },
      { german: "hell", pos: "adjective", meaning: "bright, light", exampleDe: "Das Zimmer ist sehr hell.", exampleEn: "The room is very bright.", opposites: ["dunkel"], difficulty: 1 },
      { german: "dunkel", pos: "adjective", meaning: "dark", exampleDe: "Im Winter wird es früh dunkel.", exampleEn: "In winter it gets dark early.", opposites: ["hell"], difficulty: 1 },
      { german: "wohnen", pos: "verb", meaning: "to live, to reside", exampleDe: "Wir wohnen im dritten Stock.", exampleEn: "We live on the third floor.", difficulty: 1 },
      { german: "umziehen", pos: "verb", meaning: "to move (house)", exampleDe: "Wir ziehen nächsten Monat um.", exampleEn: "We're moving next month.", memoryTip: "Separable: ich ziehe um. Same verb also means changing clothes (sich umziehen)!", difficulty: 2 },
    ],
  },
  {
    slug: "einkaufen-geld",
    levelCode: "A2",
    title: "Einkaufen & Geld",
    description: "Shopping, prices and money matters.",
    icon: "shopping-cart",
    words: [
      { german: "der Supermarkt", article: "der", plural: "Supermärkte", meaning: "supermarket", exampleDe: "Ich gehe schnell in den Supermarkt.", exampleEn: "I'm quickly going to the supermarket.", difficulty: 1 },
      { german: "der Laden", article: "der", plural: "Läden", meaning: "shop, store", exampleDe: "Der Laden macht um acht auf.", exampleEn: "The shop opens at eight.", synonyms: ["das Geschäft"], difficulty: 2 },
      { german: "der Preis", article: "der", plural: "Preise", ipa: "pʁaɪ̯s", meaning: "price", exampleDe: "Die Preise sind gestiegen.", exampleEn: "Prices have gone up.", difficulty: 1 },
      { german: "das Geld", article: "das", ipa: "ɡɛlt", meaning: "money", exampleDe: "Ich habe kein Geld dabei.", exampleEn: "I don't have any money on me.", difficulty: 1 },
      { german: "teuer", pos: "adjective", ipa: "ˈtɔʏ̯ɐ", meaning: "expensive", exampleDe: "Das Hotel ist zu teuer.", exampleEn: "The hotel is too expensive.", opposites: ["billig", "günstig"], difficulty: 1 },
      { german: "billig", pos: "adjective", meaning: "cheap", exampleDe: "Das T-Shirt war sehr billig.", exampleEn: "The T-shirt was very cheap.", synonyms: ["günstig"], opposites: ["teuer"], memoryTip: "'günstig' sounds nicer — billig can imply bad quality.", difficulty: 1 },
      { german: "kosten", pos: "verb", meaning: "to cost", exampleDe: "Was kostet das?", exampleEn: "How much does that cost?", difficulty: 1 },
      { german: "bar", pos: "adverb", meaning: "in cash", exampleDe: "Kann ich bar bezahlen?", exampleEn: "Can I pay in cash?", expressions: [{ de: "Nur Bargeld", en: "Cash only" }], memoryTip: "Germany still loves cash — always have some!", difficulty: 2 },
      { german: "die Karte", article: "die", plural: "Karten", meaning: "card; menu; map", exampleDe: "Zahlen Sie mit Karte?", exampleEn: "Are you paying by card?", difficulty: 1 },
      { german: "die Kasse", article: "die", plural: "Kassen", meaning: "checkout, till", exampleDe: "Bitte zahlen Sie an der Kasse.", exampleEn: "Please pay at the checkout.", difficulty: 2 },
      { german: "die Tüte", article: "die", plural: "Tüten", meaning: "bag (plastic/paper)", exampleDe: "Brauchen Sie eine Tüte?", exampleEn: "Do you need a bag?", difficulty: 2 },
      { german: "das Angebot", article: "das", plural: "Angebote", meaning: "offer, special deal", exampleDe: "Äpfel sind heute im Angebot.", exampleEn: "Apples are on offer today.", difficulty: 2 },
      { german: "der Rabatt", article: "der", plural: "Rabatte", meaning: "discount", exampleDe: "Es gibt zwanzig Prozent Rabatt.", exampleEn: "There's a twenty percent discount.", difficulty: 2 },
      { german: "die Größe", article: "die", plural: "Größen", meaning: "size", exampleDe: "Haben Sie das in Größe M?", exampleEn: "Do you have this in size M?", difficulty: 2 },
      { german: "anprobieren", pos: "verb", meaning: "to try on", exampleDe: "Kann ich die Jacke anprobieren?", exampleEn: "Can I try on the jacket?", memoryTip: "Separable: ich probiere sie an.", difficulty: 2 },
      { german: "umtauschen", pos: "verb", meaning: "to exchange (goods)", exampleDe: "Ich möchte das Hemd umtauschen.", exampleEn: "I'd like to exchange the shirt.", difficulty: 3 },
      { german: "die Quittung", article: "die", plural: "Quittungen", meaning: "receipt", exampleDe: "Brauchen Sie die Quittung?", exampleEn: "Do you need the receipt?", synonyms: ["der Kassenbon"], difficulty: 2 },
      { german: "geöffnet", pos: "adjective", meaning: "open (shop)", exampleDe: "Sonntags ist der Laden nicht geöffnet.", exampleEn: "The shop isn't open on Sundays.", opposites: ["geschlossen"], memoryTip: "Sunday shopping doesn't exist in Germany — plan ahead!", difficulty: 2 },
      { german: "geschlossen", pos: "adjective", meaning: "closed", exampleDe: "Die Apotheke ist geschlossen.", exampleEn: "The pharmacy is closed.", opposites: ["geöffnet"], difficulty: 2 },
      { german: "das Sonderangebot", article: "das", plural: "Sonderangebote", meaning: "special offer", exampleDe: "Das war ein Sonderangebot.", exampleEn: "That was a special offer.", difficulty: 3 },
    ],
  },
  {
    slug: "gesundheit-koerper",
    levelCode: "A2",
    title: "Gesundheit & Körper",
    description: "Body parts, illness and going to the doctor.",
    icon: "stethoscope",
    words: [
      { german: "der Körper", article: "der", plural: "Körper", meaning: "body", exampleDe: "Sport ist gut für den Körper.", exampleEn: "Sport is good for the body.", difficulty: 1 },
      { german: "der Kopf", article: "der", plural: "Köpfe", ipa: "kɔpf", meaning: "head", exampleDe: "Mir tut der Kopf weh.", exampleEn: "My head hurts.", difficulty: 1 },
      { german: "der Bauch", article: "der", plural: "Bäuche", meaning: "belly, stomach", exampleDe: "Ich habe Bauchschmerzen.", exampleEn: "I have a stomachache.", difficulty: 1 },
      { german: "der Rücken", article: "der", plural: "Rücken", meaning: "back", exampleDe: "Mein Rücken tut weh.", exampleEn: "My back hurts.", difficulty: 2 },
      { german: "die Hand", article: "die", plural: "Hände", ipa: "hant", meaning: "hand", exampleDe: "Wasch dir die Hände!", exampleEn: "Wash your hands!", difficulty: 1 },
      { german: "das Bein", article: "das", plural: "Beine", meaning: "leg", exampleDe: "Er hat sich das Bein gebrochen.", exampleEn: "He broke his leg.", difficulty: 1 },
      { german: "der Arzt", article: "der", plural: "Ärzte", ipa: "aːɐ̯tst", meaning: "doctor (m)", exampleDe: "Ich muss zum Arzt gehen.", exampleEn: "I have to go to the doctor.", difficulty: 1 },
      { german: "die Ärztin", article: "die", plural: "Ärztinnen", meaning: "doctor (f)", exampleDe: "Die Ärztin ist sehr nett.", exampleEn: "The doctor is very nice.", difficulty: 1 },
      { german: "die Praxis", article: "die", plural: "Praxen", meaning: "doctor's office", exampleDe: "Die Praxis ist montags geschlossen.", exampleEn: "The practice is closed on Mondays.", difficulty: 2 },
      { german: "der Schmerz", article: "der", plural: "Schmerzen", meaning: "pain", exampleDe: "Ich habe starke Schmerzen.", exampleEn: "I'm in a lot of pain.", expressions: [{ de: "Kopfschmerzen / Halsschmerzen", en: "headache / sore throat" }], difficulty: 2 },
      { german: "krank", pos: "adjective", ipa: "kʁaŋk", meaning: "sick, ill", exampleDe: "Ich bin seit Montag krank.", exampleEn: "I've been sick since Monday.", opposites: ["gesund"], difficulty: 1 },
      { german: "gesund", pos: "adjective", ipa: "ɡəˈzʊnt", meaning: "healthy", exampleDe: "Obst ist gesund.", exampleEn: "Fruit is healthy.", opposites: ["krank"], difficulty: 1 },
      { german: "das Fieber", article: "das", meaning: "fever", exampleDe: "Das Kind hat hohes Fieber.", exampleEn: "The child has a high fever.", difficulty: 2 },
      { german: "die Erkältung", article: "die", plural: "Erkältungen", meaning: "cold (illness)", exampleDe: "Ich habe eine Erkältung.", exampleEn: "I have a cold.", memoryTip: "From 'kalt' (cold) — the illness from the cold.", difficulty: 2 },
      { german: "husten", pos: "verb", meaning: "to cough", exampleDe: "Er hustet die ganze Nacht.", exampleEn: "He coughs all night.", difficulty: 2 },
      { german: "das Medikament", article: "das", plural: "Medikamente", meaning: "medicine", exampleDe: "Nehmen Sie das Medikament zweimal täglich.", exampleEn: "Take the medicine twice a day.", difficulty: 2 },
      { german: "die Apotheke", article: "die", plural: "Apotheken", meaning: "pharmacy", exampleDe: "Die Apotheke ist neben dem Bahnhof.", exampleEn: "The pharmacy is next to the station.", memoryTip: "Big red 'A' sign — Apotheke, not the drugstore (Drogerie)!", difficulty: 2 },
      { german: "das Rezept", article: "das", plural: "Rezepte", meaning: "prescription; recipe", exampleDe: "Sie bekommen ein Rezept.", exampleEn: "You'll get a prescription.", difficulty: 2 },
      { german: "die Krankenversicherung", article: "die", plural: "Krankenversicherungen", meaning: "health insurance", exampleDe: "Haben Sie eine Krankenversicherung?", exampleEn: "Do you have health insurance?", difficulty: 3 },
      { german: "wehtun", pos: "verb", meaning: "to hurt", exampleDe: "Mein Hals tut weh.", exampleEn: "My throat hurts.", memoryTip: "Dative! MIR tut der Kopf weh — the head hurts TO ME.", difficulty: 2 },
    ],
  },
  {
    slug: "reisen-verkehr",
    levelCode: "A2",
    title: "Reisen & Verkehr",
    description: "Trains, tickets, directions and holidays.",
    icon: "plane",
    words: [
      { german: "die Reise", article: "die", plural: "Reisen", ipa: "ˈʁaɪ̯zə", meaning: "trip, journey", exampleDe: "Gute Reise!", exampleEn: "Have a good trip!", difficulty: 1 },
      { german: "der Urlaub", article: "der", plural: "Urlaube", meaning: "vacation", exampleDe: "Im August habe ich Urlaub.", exampleEn: "I'm on vacation in August.", expressions: [{ de: "in den Urlaub fahren", en: "to go on vacation" }], difficulty: 1 },
      { german: "der Zug", article: "der", plural: "Züge", ipa: "tsuːk", meaning: "train", exampleDe: "Der Zug hat Verspätung.", exampleEn: "The train is delayed.", memoryTip: "A sentence you'll hear a lot at German stations…", difficulty: 1 },
      { german: "der Bahnhof", article: "der", plural: "Bahnhöfe", meaning: "train station", exampleDe: "Wie komme ich zum Bahnhof?", exampleEn: "How do I get to the station?", expressions: [{ de: "der Hauptbahnhof (Hbf)", en: "main station" }], difficulty: 1 },
      { german: "das Gleis", article: "das", plural: "Gleise", meaning: "platform, track", exampleDe: "Der Zug fährt von Gleis 7 ab.", exampleEn: "The train departs from platform 7.", difficulty: 2 },
      { german: "die Fahrkarte", article: "die", plural: "Fahrkarten", meaning: "ticket (transport)", exampleDe: "Ich habe die Fahrkarte online gekauft.", exampleEn: "I bought the ticket online.", synonyms: ["das Ticket"], difficulty: 2 },
      { german: "die Verspätung", article: "die", plural: "Verspätungen", meaning: "delay", exampleDe: "Der Zug hat 20 Minuten Verspätung.", exampleEn: "The train is 20 minutes late.", difficulty: 2 },
      { german: "umsteigen", pos: "verb", meaning: "to change (trains)", exampleDe: "In Köln müssen Sie umsteigen.", exampleEn: "You have to change trains in Cologne.", memoryTip: "Separable: ich steige um.", difficulty: 2 },
      { german: "abfahren", pos: "verb", meaning: "to depart", exampleDe: "Wann fährt der Bus ab?", exampleEn: "When does the bus leave?", opposites: ["ankommen"], difficulty: 2 },
      { german: "ankommen", pos: "verb", meaning: "to arrive", exampleDe: "Wir kommen um 18 Uhr an.", exampleEn: "We arrive at 6 pm.", opposites: ["abfahren"], difficulty: 2 },
      { german: "das Flugzeug", article: "das", plural: "Flugzeuge", meaning: "airplane", exampleDe: "Das Flugzeug landet pünktlich.", exampleEn: "The plane is landing on time.", difficulty: 1 },
      { german: "der Flughafen", article: "der", plural: "Flughäfen", meaning: "airport", exampleDe: "Wir fahren um sechs zum Flughafen.", exampleEn: "We're going to the airport at six.", difficulty: 2 },
      { german: "das Hotel", article: "das", plural: "Hotels", meaning: "hotel", exampleDe: "Ich habe ein Zimmer im Hotel reserviert.", exampleEn: "I've reserved a room at the hotel.", difficulty: 1 },
      { german: "der Koffer", article: "der", plural: "Koffer", meaning: "suitcase", exampleDe: "Mein Koffer ist zu schwer.", exampleEn: "My suitcase is too heavy.", difficulty: 2 },
      { german: "der Ausweis", article: "der", plural: "Ausweise", meaning: "ID card", exampleDe: "Ihren Ausweis, bitte.", exampleEn: "Your ID, please.", synonyms: ["der Personalausweis"], difficulty: 2 },
      { german: "die Haltestelle", article: "die", plural: "Haltestellen", meaning: "(bus/tram) stop", exampleDe: "Die Haltestelle ist gleich da vorne.", exampleEn: "The stop is right up ahead.", difficulty: 2 },
      { german: "geradeaus", pos: "adverb", meaning: "straight ahead", exampleDe: "Gehen Sie immer geradeaus.", exampleEn: "Keep going straight ahead.", difficulty: 2 },
      { german: "links", pos: "adverb", meaning: "left", exampleDe: "Biegen Sie links ab.", exampleEn: "Turn left.", opposites: ["rechts"], difficulty: 1 },
      { german: "rechts", pos: "adverb", meaning: "right", exampleDe: "Die Bank ist rechts.", exampleEn: "The bank is on the right.", opposites: ["links"], difficulty: 1 },
      { german: "pünktlich", pos: "adjective", meaning: "punctual, on time", exampleDe: "Bitte sei pünktlich!", exampleEn: "Please be on time!", memoryTip: "The most German adjective in existence.", difficulty: 2 },
    ],
  },
  {
    slug: "arbeit-beruf-a2",
    levelCode: "A2",
    title: "Arbeit & Beruf",
    description: "Jobs, the office and everyday work language.",
    icon: "briefcase",
    words: [
      { german: "die Arbeit", article: "die", plural: "Arbeiten", ipa: "ˈaʁbaɪ̯t", meaning: "work", exampleDe: "Ich fahre mit dem Rad zur Arbeit.", exampleEn: "I cycle to work.", difficulty: 1 },
      { german: "der Beruf", article: "der", plural: "Berufe", meaning: "profession", exampleDe: "Was sind Sie von Beruf?", exampleEn: "What is your profession?", difficulty: 1 },
      { german: "der Job", article: "der", plural: "Jobs", meaning: "job", exampleDe: "Sie hat einen neuen Job gefunden.", exampleEn: "She found a new job.", synonyms: ["die Stelle"], difficulty: 1 },
      { german: "die Firma", article: "die", plural: "Firmen", meaning: "company", exampleDe: "Die Firma hat 200 Mitarbeiter.", exampleEn: "The company has 200 employees.", synonyms: ["das Unternehmen"], difficulty: 1 },
      { german: "der Chef", article: "der", plural: "Chefs", ipa: "ʃɛf", meaning: "boss (m)", exampleDe: "Mein Chef ist sehr fair.", exampleEn: "My boss is very fair.", memoryTip: "False friend: not a cook! The cook is 'der Koch'.", difficulty: 1 },
      { german: "der Kollege", article: "der", plural: "Kollegen", meaning: "colleague (m)", exampleDe: "Meine Kollegen sind hilfsbereit.", exampleEn: "My colleagues are helpful.", difficulty: 1 },
      { german: "das Büro", article: "das", plural: "Büros", ipa: "byˈʁoː", meaning: "office", exampleDe: "Ich arbeite montags im Büro.", exampleEn: "On Mondays I work at the office.", difficulty: 1 },
      { german: "die Besprechung", article: "die", plural: "Besprechungen", meaning: "meeting", exampleDe: "Um zehn haben wir eine Besprechung.", exampleEn: "We have a meeting at ten.", synonyms: ["das Meeting"], difficulty: 2 },
      { german: "das Gehalt", article: "das", plural: "Gehälter", meaning: "salary", exampleDe: "Das Gehalt wird am Monatsende gezahlt.", exampleEn: "The salary is paid at the end of the month.", synonyms: ["der Lohn"], difficulty: 2 },
      { german: "verdienen", pos: "verb", meaning: "to earn", exampleDe: "Wie viel verdient man in diesem Beruf?", exampleEn: "How much do you earn in this profession?", difficulty: 2 },
      { german: "die Ausbildung", article: "die", plural: "Ausbildungen", meaning: "vocational training", exampleDe: "Er macht eine Ausbildung als Elektriker.", exampleEn: "He's doing an apprenticeship as an electrician.", difficulty: 2 },
      { german: "die Bewerbung", article: "die", plural: "Bewerbungen", meaning: "job application", exampleDe: "Ich habe drei Bewerbungen geschrieben.", exampleEn: "I've written three applications.", difficulty: 2 },
      { german: "der Lebenslauf", article: "der", plural: "Lebensläufe", meaning: "CV, résumé", exampleDe: "Schicken Sie bitte Ihren Lebenslauf.", exampleEn: "Please send your CV.", memoryTip: "Literally 'life-run' — your life at a glance.", difficulty: 2 },
      { german: "die Erfahrung", article: "die", plural: "Erfahrungen", meaning: "experience", exampleDe: "Sie hat viel Erfahrung im Verkauf.", exampleEn: "She has a lot of sales experience.", difficulty: 2 },
      { german: "kündigen", pos: "verb", meaning: "to quit, to terminate", exampleDe: "Er hat letzte Woche gekündigt.", exampleEn: "He quit last week.", difficulty: 3 },
      { german: "die Überstunde", article: "die", plural: "Überstunden", meaning: "overtime hour", exampleDe: "Ich habe diese Woche fünf Überstunden gemacht.", exampleEn: "I did five hours of overtime this week.", difficulty: 3 },
      { german: "der Kunde", article: "der", plural: "Kunden", meaning: "customer (m)", exampleDe: "Der Kunde ist König.", exampleEn: "The customer is king.", difficulty: 2 },
      { german: "der Vertrag", article: "der", plural: "Verträge", meaning: "contract", exampleDe: "Ich habe den Vertrag unterschrieben.", exampleEn: "I signed the contract.", difficulty: 2 },
      { german: "der Urlaubstag", article: "der", plural: "Urlaubstage", meaning: "vacation day", exampleDe: "Ich habe noch zehn Urlaubstage.", exampleEn: "I still have ten vacation days.", difficulty: 2 },
      { german: "anstrengend", pos: "adjective", meaning: "exhausting, demanding", exampleDe: "Die Arbeit ist anstrengend, aber schön.", exampleEn: "The work is exhausting but nice.", synonyms: ["stressig"], difficulty: 2 },
    ],
  },
];
